#!/usr/bin/env python3
"""Read-only exact fragment/bundle agreement for a checked snapshot; no runtime executed."""
import argparse,hashlib,json
from pathlib import Path
PARTS=('core','base','effects','readback','foreign')
HEADER='// Generated by src/runtime/js/build.mjs; edit the fragments.\n'
BUILD_SOURCE="""// Concatenate primitive runtime fragments for embedding in standalone output.
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'../..');
const parts=['core','base','effects','readback','foreign'];
const source='// Generated by src/runtime/js/build.mjs; edit the fragments.\\n'+parts.map(n=>fs.readFileSync(path.join(import.meta.dirname,n+'.mjs'),'utf8')).join('\\n');
fs.writeFileSync(path.join(root,'runtime.mjs'),source);
"""
def ident(p):
 p=Path(p).resolve();raw=p.read_bytes();return dict(file=str(p),sha256=hashlib.sha256(raw).hexdigest(),bytes=len(raw))
def verify_source(src):
 src=Path(src).resolve();builder=src/'runtime/js/build.mjs';assert builder.read_bytes()==BUILD_SOURCE.encode('utf8'),'Runtime build recipe changed; explicit reviewed successor required'
 fragments=[src/('runtime/js/'+name+'.mjs') for name in PARTS]
 # Mirror Node readFileSync(utf8), join newline and writeFileSync exactly. Strict
 # UTF8 rejects invalid fragments rather than silently replacing malformed bytes.
 generated=HEADER+'\n'.join(f.read_bytes().decode('utf8') for f in fragments)
 bundle=src/'runtime.mjs';assert bundle.read_bytes()==generated.encode('utf8'),'Generated runtime.mjs diverges from core/base/effects/readback/foreign; assemble runtime before checked build'
 return dict(complete=True,**{'pass':True},build=ident(builder),fragments=[ident(f) for f in fragments],bundle=ident(bundle),assembledSha256=hashlib.sha256(generated.encode('utf8')).hexdigest())
def verify_attempt(attempt):
 attempt=Path(attempt).resolve();m=json.loads((attempt/'attempt.json').read_text());assert m['checked']
 result=verify_source(attempt/'snapshot/src');assert result['bundle']['sha256']==m['runtime']['sha256']
 assert Path(m['runtime']['file']).resolve()==attempt/'snapshot/src/runtime.mjs'
 return dict(kind='phase43-runtime-fragment-bundle-agreement',complete=True,**{'pass':True},attempt=ident(attempt/'attempt.json'),runtime=m['runtime'],producer=ident(__file__),snapshot=result)
def main():
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('--attempt',type=Path,required=True);p.add_argument('--current-src',type=Path);p.add_argument('--receipt',type=Path);a=p.parse_args()
 report=verify_attempt(a.attempt)
 if a.current_src:report['current']=verify_source(a.current_src)
 if a.receipt:
  assert not a.receipt.exists();a.receipt.parent.mkdir(parents=True,exist_ok=True);a.receipt.write_text(json.dumps(report,indent=2)+'\n')
 print(json.dumps(report))
if __name__=='__main__':main()
