// Instrument actual checked emission; no manual private proof/activation flags.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
const [actualArg,parentArg,outArg]=process.argv.slice(2);assert(outArg,'actual-derive.mjs ACTUAL_MODULE PREVIOUS_CLOSURE_DERIVED NEW_OUT');const out=path.resolve(outArg);assert(!fs.existsSync(out));const identity=p=>({path:fs.realpathSync(p),sha256:createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
const parentFile=path.join(parentArg,'derive.json'),parent=JSON.parse(fs.readFileSync(parentFile));assert.equal(parent.kind,'phase43-composition-materialized');const actual=identity(actualArg),receiptFile=identity(actualArg+'.json'),receipt=JSON.parse(fs.readFileSync(receiptFile.path));assert.equal(receipt.kind,'bend-program-checked-emission');assert(receipt.complete&&receipt.observation.checked);assert.equal(receipt.output.sha256,actual.sha256);const previousReceipt=JSON.parse(fs.readFileSync(parent.baseline.path+'.json'));assert.equal(receipt.input.sha256,previousReceipt.input.sha256);
const parserSource=process.binding('natives')['internal/deps/acorn/acorn/dist/acorn'],pm={exports:{}};new Function('module','exports',parserSource)(pm,pm.exports);const parse=s=>pm.exports.parse(s,{ecmaVersion:'latest',sourceType:'module'});
function walk(n,f){if(!n||typeof n!=='object')return;f(n);for(const[k,v]of Object.entries(n)){if(k==='start'||k==='end')continue;if(Array.isArray(v))v.forEach(x=>walk(x,f));else if(v?.type)walk(v,f);}}
const report={kind:'phase43-actual-source-callback',complete:false,certified:true,rootName:parent.rootName,dependencies:parent.dependencies,actual,baseline:parent.baseline,typescript:parent.typescript,catalog:parent.catalog,modules:[],inputs:[identity(import.meta.filename),identity(parentFile),actual,receiptFile,parent.baseline,parent.typescript,parent.catalog],scope:'Exact actual checked source emission; diagnostic counters/observer attach to its real scalar root, environment construction and application paths. No manually admitted root.'};
fs.mkdirSync(out);
for(const [variant,row]of [['original',parent.baseline],['actual',actual]])for(const counters of [false,true]){let text=fs.readFileSync(row.path,'utf8');if(counters){const tree=parse(text),edits=[];const count={roots:0,direct:0,leaves:0,identities:0,compositions:0,generic:0};if(variant==='actual'){
 const marker='/* private materialized callback environment */';assert.equal(text.split(marker).length-1,1);let selected;for(const s of tree.body)if(s.expression?.left?.object?.name==='G'&&s.expression.left.property.value===parent.rootName)selected=s;assert(selected&&text.slice(selected.start,selected.end).includes(marker));edits.push({at:text.indexOf(marker)+marker.length,text:'++$p43ActualCount.roots;'});
 let leaves=0,identities=0,compositions=0,direct=0,observed=0;walk(selected,n=>{
  if(n.type==='ExpressionStatement'&&n.expression.type==='CallExpression'&&n.expression.callee.object?.name==='$cb_pending'&&n.expression.callee.property.name==='push'){edits.push({at:n.end,text:'++$p43ActualCount.leaves;'});leaves++;}
  if(n.type==='VariableDeclaration'&&n.declarations.some(d=>d.id.name==='$cb_environment')){edits.push({at:n.end,text:'++$p43ActualCount.identities;'});identities++;}
  if(n.type==='ExpressionStatement'&&n.expression.type==='AssignmentExpression'&&n.expression.left.name==='$cb_environment'&&n.expression.right.type==='ObjectExpression'){edits.push({at:n.end,text:'++$p43ActualCount.compositions;'});compositions++;}
  if(n.type==='VariableDeclaration'&&n.declarations.some(d=>d.id.name==='$cb_value')){edits.push({at:n.start,text:'$p43ActualEnvironment=$cb_environment;'});observed++;}
  if(n.type==='ExpressionStatement'&&n.expression.type==='AssignmentExpression'&&n.expression.left.name==='$cb_value'){edits.push({at:n.end,text:'++$p43ActualCount.direct;'});direct++;}
 });assert.deepEqual({leaves,identities,compositions,direct,observed},{leaves:1,identities:1,compositions:1,direct:1,observed:1});
 }
 let apply;walk(tree,n=>{if(n.type==='FunctionDeclaration'&&n.id.name==='apply')apply=n;});assert(apply);edits.push({at:apply.body.start+1,text:'++$p43ActualCount.generic;'});for(const e of edits.sort((a,b)=>b.at-a.at))text=text.slice(0,e.at)+e.text+text.slice(e.at);
 text+='\nconst $p43ActualCount='+JSON.stringify(count)+';let $p43ActualEnvironment=null;export const callbackState=()=>({...$p43ActualCount,active:regionProof!==null});export const callbackReset=()=>{for(const key of Object.keys($p43ActualCount))$p43ActualCount[key]=0;$p43ActualEnvironment=null;};export const callbackLastEnvironment=()=>$p43ActualEnvironment;\n';parse(text);
 }const file=path.join(out,variant+(counters?'.diagnostic.mjs':'.clean.mjs'));fs.writeFileSync(file,text,{flag:'wx'});report.modules.push({variant,counters,...identity(file)});}
report.complete=true;fs.writeFileSync(path.join(out,'derive.json'),JSON.stringify(report,null,2)+'\n');const config=JSON.parse(fs.readFileSync(path.join(parentArg,'compare.json')));config.inputs=[path.join(out,'derive.json')];for(const c of config.cases)c.modules={original:path.join(out,'original.clean.mjs'),actual:path.join(out,'actual.clean.mjs'),typescript:parent.typescript.path};fs.writeFileSync(path.join(out,'compare.json'),JSON.stringify(config,null,2)+'\n');console.log(JSON.stringify({complete:true,out}));
