// Phase43 materialized defunctionalized environments. Frozen predecessor inputs.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
const [previousArg,outArg]=process.argv.slice(2);assert(outArg,'environment-derive.mjs PREVIOUS_DERIVED NEW_OUT');const previous=fs.realpathSync(previousArg),out=path.resolve(outArg);assert(!fs.existsSync(out));
const identity=p=>({path:fs.realpathSync(p),sha256:createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
const parent=JSON.parse(fs.readFileSync(path.join(previous,'derive.json')));assert.equal(parent.kind,'phase43-composition-materialized');assert(parent.complete);for(const row of parent.modules)assert.equal(identity(row.path).sha256,row.sha256);
const parserSource=process.binding('natives')['internal/deps/acorn/acorn/dist/acorn'],pm={exports:{}};new Function('module','exports',parserSource)(pm,pm.exports);const parse=s=>pm.exports.parse(s,{ecmaVersion:'latest',sourceType:'module'});
function walk(n,f){if(!n||typeof n!=='object')return;f(n);for(const[k,v]of Object.entries(n)){if(k==='start'||k==='end')continue;if(Array.isArray(v))v.forEach(x=>walk(x,f));else if(v?.type)walk(v,f);}}
const source=fs.readFileSync(parent.baseline.path,'utf8'),ast=parse(source),chainName=parent.dependencies[1];let chain;for(const s of ast.body)if(s.expression?.left?.object?.name==='G'&&s.expression.left.property.value===chainName)chain=s;assert(chain);
const calls=[];walk(chain,n=>{if(n.type==='CallExpression'&&n.callee.type==='ArrowFunctionExpression'&&n.callee.params.length===1)calls.push(n);});assert.equal(calls.length,1);const captureCall=calls[0],captureExpression=source.slice(captureCall.arguments[0].start,captureCall.arguments[0].end);assert.equal(captureCall.arguments.length,1);
const outer=[];walk(chain,n=>{if(n.type==='CallExpression'&&n.callee.name==='fn'&&n.arguments[1]?.type==='FunctionExpression'&&n.arguments[1].body.start<captureCall.start&&n.arguments[1].body.end>captureCall.end)outer.push(n);});assert.equal(outer.length,1);const predecessor=outer[0].arguments[1].body.body[0].declarations[0].id.name;
const report={...parent,kind:'phase43-defunctionalized-materialized',parent:identity(path.join(previous,'derive.json')),producer:identity(import.meta.filename),complete:false,modules:[],inputs:[identity(import.meta.filename),identity(path.join(previous,'derive.json')),...parent.modules.map(r=>identity(r.path)),parent.baseline,parent.typescript],scope:'Complete private first-order identity/scalar/composition environment. Descending capture creation, base identity, ascending composition materialization, then ordered application. No closed-form sum or fusion.'};
fs.mkdirSync(out);
for(const row of parent.modules){const name=row.variant+(row.counters?'.diagnostic.mjs':'.clean.mjs'),file=path.join(out,name);fs.copyFileSync(row.path,file);report.modules.push({...row,...identity(file)});}
for(const counters of [false,true]){
 const input=parent.modules.find(r=>r.variant==='direct'&&r.counters===counters);let text=fs.readFileSync(input.path,'utf8');const tree=parse(text);let run,known;for(const s of tree.body){if(s.type==='FunctionDeclaration'&&s.id.name==='$p43Run')run=s;if(s.type==='FunctionDeclaration'&&s.id.name==='$p43KnownOffset')known=s;}assert(run&&known);
 const worker='function $p43BuildEnvironment(n){const pending=[];while(n!==0n){const '+predecessor+'=n-1n;const capture='+captureExpression+';const leaf={tag:1,capture};'+(counters?'++$p43Count.leaves;':'')+'pending.push(leaf);n='+predecessor+';}let environment={tag:0};'+(counters?'++$p43Count.identities;':'')+'while(pending.length){environment={tag:2,left:pending.pop(),right:environment};'+(counters?'++$p43Count.compositions;':'')+'}return environment;}\n'+
 'function $p43ApplyEnvironment(environment,value){while(environment.tag===2){'+(counters?'++$p43Count.direct;':'')+'value=$p43KnownOffset(environment.left.capture,value);environment=environment.right;}return value;}\n'+
 'function $p43Run(a){'+(counters?'++$p43Count.roots;':'')+'const previous=regionProofOpen($p43Names);try{const environment=$p43BuildEnvironment(BigInt(a[0]));return $p43ApplyEnvironment(environment,a[1]);}finally{regionProofClose(previous);}}';
 text=text.slice(0,run.start)+worker+text.slice(run.end);
 if(counters){text=text.replace('const $p43Count={roots:0,direct:0};','const $p43Count={roots:0,direct:0,leaves:0,identities:0,compositions:0};').replace('$p43Count.roots=0;$p43Count.direct=0;','for(const key of Object.keys($p43Count))$p43Count[key]=0;');text+='\nexport function callbackEnvironment(n){if(!$p43Eligible([n,0]))bad("diagnostic environment refused");const previous=regionProofOpen($p43Names);try{return $p43BuildEnvironment(BigInt(n));}finally{regionProofClose(previous);}}\nexport const callbackApplyEnvironment=(environment,value)=>$p43ApplyEnvironment(environment,value);\n';}
 parse(text);const file=path.join(out,'environment'+(counters?'.diagnostic.mjs':'.clean.mjs'));fs.writeFileSync(file,text,{flag:'wx'});report.modules.push({variant:'environment',counters,...identity(file)});
}
report.complete=true;fs.writeFileSync(path.join(out,'derive.json'),JSON.stringify(report,null,2)+'\n');const config=JSON.parse(fs.readFileSync(path.join(previous,'compare.json')));config.inputs=[path.join(out,'derive.json')];for(const c of config.cases){for(const v of ['original','scoped','direct'])c.modules[v]=path.join(out,v+'.clean.mjs');c.modules.environment=path.join(out,'environment.clean.mjs');}fs.writeFileSync(path.join(out,'compare.json'),JSON.stringify(config,null,2)+'\n');console.log(JSON.stringify({complete:true,out,certified:false}));
