import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
const[dir,out]=process.argv.slice(2);assert(dir&&out&&!fs.existsSync(out));fs.mkdirSync(out);const prep=JSON.parse(fs.readFileSync(path.join(dir,'preparation.json')));assert.equal(prep.kind,'phase43-map-whole-discriminator');
const hash=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex');const mods={};for(const role of ['original','amortized','whole']){assert.equal(hash(prep.modules[role].file),prep.modules[role].sha256);mods[role]=await import(pathToFileURL(prep.modules[role].file));}
const observe=f=>{try{return {value:f()};}catch(e){return {error:{name:e.name,message:e.message}};}};
let values=0,boundaries=0;const checks=[];
function entries(m){const out=[],stack=[m];while(stack.length){const n=stack.pop();if(n.$==='MLeaf')out.push(n.a);else if(n.$==='MNode'){stack.push(n.a[2]);stack.push(n.a[1]);}else assert.equal(n.$,'MTip');}return out;}
const fixtures=[[],[['',0]],[['a',1],['ab',2],['a',3],['b',4],['a\0',5]],Array.from({length:128},(_,i)=>['key'+i,Math.imul(i,17)>>>0])];
for(const rows of fixtures)for(const removals of [[],['missing','a','key0','key17','']]){const results=[];for(const role of Object.keys(mods)){const r=mods[role].phase43MapDebug.fixture(rows,removals);results.push({entries:entries(r.map),pops:r.pops});assert.equal(mods[role].phase43MapDebug.proof(),false);}assert.deepEqual(results[1],results[0]);assert.deepEqual(results[2],results[0]);const expected=new Map(rows);for(const k of removals)expected.delete(k);assert.deepEqual(results[0].entries,[...expected].sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:0));values++;}
for(const args of [[0,0],[1,17],[7,31],[32,17],[128,123]]){const rs=Object.values(mods).map(m=>m.default[prep.root](...args));assert.equal(rs[1],rs[0]);assert.equal(rs[2],rs[0]);values++;checks.push({args,result:rs[0]});}
const deep=Object.values(mods).map(m=>m.phase43MapDebug.deep(12000));assert.deepEqual(deep[1],deep[0]);assert.deepEqual(deep[2],deep[0]);values++;
assert(mods.amortized.phase43MapDebug.counts().bits>0);assert(mods.whole.phase43MapDebug.counts().operations>0);
for(const name of prep.dependencies)for(const mode of ['binding','getter','throw','reentry']){const results=[];for(const role of Object.keys(mods)){const m=mods[role],saved=Object.getOwnPropertyDescriptor(m.G,name),events=[],before=m.phase43MapDebug.counts().entries;let entered=false;const wrapped={...saved.value,code:function(...args){events.push('code');return saved.value.code.apply(this,args);}};if(mode==='binding')Object.defineProperty(m.G,name,{...saved,value:wrapped});else Object.defineProperty(m.G,name,{configurable:true,enumerable:true,get(){events.push('get');if(mode==='throw')throw Error('p43 sentinel');if(mode==='reentry'&&!entered){entered=true;events.push(['inner',m.default[prep.root](1,17)]);}return wrapped;}});let result;try{result=observe(()=>m.default[prep.root](2,17));}finally{Object.defineProperty(m.G,name,saved);}assert.equal(m.phase43MapDebug.counts().entries,before);assert.equal(m.phase43MapDebug.proof(),false);results.push({result,events});}assert.deepEqual(results[1],results[0],name+' '+mode);assert.deepEqual(results[2],results[0],name+' '+mode);boundaries++;}
for(const[target,name]of [[String.prototype,'codePointAt'],[String.prototype,'slice'],[String,'fromCodePoint']])for(const mode of ['return','throw','reentry']){const results=[];for(const role of Object.keys(mods)){const m=mods[role],saved=Object.getOwnPropertyDescriptor(target,name),events=[],before=m.phase43MapDebug.counts().entries;let entered=false;Object.defineProperty(target,name,{...saved,value:function(...args){events.push(name);if(mode==='throw')throw Error('p43 host sentinel');if(mode==='reentry'&&!entered){entered=true;events.push(['inner',m.default[prep.root](1,17)]);}return saved.value.apply(this,args);}});let result;try{result=observe(()=>m.default[prep.root](2,17));}finally{Object.defineProperty(target,name,saved);}assert.equal(m.phase43MapDebug.counts().entries,before);assert.equal(m.phase43MapDebug.proof(),false);results.push({result,events});}assert.deepEqual(results[1],results[0],name+' '+mode);assert.deepEqual(results[2],results[0],name+' '+mode);boundaries++;}
for(const name of ['request','bounce','build','code','io','typeName'])for(const mode of ['get','throw','reentry']){const results=[];for(const role of Object.keys(mods)){const m=mods[role],saved=Object.getOwnPropertyDescriptor(String.prototype,name),events=[],before=m.phase43MapDebug.counts().entries;let entered=false;Object.defineProperty(String.prototype,name,{configurable:true,get(){events.push(name);if(mode==='throw')throw Error('p43 marker sentinel');if(mode==='reentry'&&!entered){entered=true;events.push(['inner',m.default[prep.root](1,17)]);}return undefined;}});let result;try{result=observe(()=>m.default[prep.root](2,17));}finally{if(saved)Object.defineProperty(String.prototype,name,saved);else delete String.prototype[name];}assert.equal(m.phase43MapDebug.counts().entries,before);assert.equal(m.phase43MapDebug.proof(),false);results.push({result,events});}assert.deepEqual(results[1],results[0],name+' '+mode);assert.deepEqual(results[2],results[0],name+' '+mode);boundaries++;}
const report={kind:'phase43-map-controls',complete:true,checked:false,compilerAdmission:false,values,boundaries,checks,counts:Object.fromEntries(Object.entries(mods).map(([r,m])=>[r,m.phase43MapDebug.counts()])),preparation:prep};fs.copyFileSync(import.meta.filename,path.join(out,'consumed-controls.mjs'));fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
