// Differential semantics and evaluation order for structurally proven choices.
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {pathToFileURL} from 'node:url';
import {inspect,project} from '../../../tools/typed-driver.mjs';
const directory=path.join(project,'build/choice-tests');fs.mkdirSync(directory,{recursive:true});
const source=path.join(project,'tests/fixtures/choice.bend');
const names=['picked','partial','loop','dynamic','reversed','ordered'];
const oracleFile=path.join(directory,'oracle.mjs'),candidateFile=path.join(directory,'candidate.mjs');
const built=spawnSync(process.execPath,[path.join(project,'tools/stage0-library.mjs'),source,oracleFile,...names],{encoding:'utf8',timeout:120000});
assert.equal(built.status,0,built.error?.message||built.stderr);
const result=await inspect(source,{mode:'library'});assert.equal(result.status,'ok',JSON.stringify(result));
assert.match(result.code,/\/\* choice \*\//,'eligible literal thunks must use the optimized path');
fs.writeFileSync(candidateFile,result.code);
const {default:actual,G}=await import(pathToFileURL(candidateFile));
const {default:oracle}=await import(pathToFileURL(oracleFile));
for(const name of names.filter(n=>n!=='loop'))for(const b of [true,false])assert.deepEqual(actual[name](b),oracle[name](b),name+' '+b);
assert.equal(actual.loop(50000),17,'tail recursion must remain trampolined');
const events=[];
G.condition={arity:1,code:args=>{events.push('condition');return args[0]},env:null,bound:[]};
G.selected={arity:1,code:args=>{events.push(String(args[0]));return args[0]},env:null,bound:[]};
assert.equal(actual.ordered(true),41n);assert.deepEqual(events,['condition','41']);
events.length=0;assert.equal(actual.ordered(false),43n);assert.deepEqual(events,['condition','43']);
const original=G.thunk;
G.thunk={arity:0,code:(...args)=>{events.push('construct');return original.code(...args)},env:original.env,bound:[]};
events.length=0;assert.equal(actual.dynamic(false),29n);assert.deepEqual(events,['construct'],'computed unselected thunk must still be evaluated');
console.log('choice oracle, partial/dynamic fallback, altered body, branch order, and 50000 tail calls passed');
