// Instrument actual compiler output; never changes its selected paths.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
import * as ref from '../../phase42/calls/bst-oracles.mjs';
const [moduleArg,baselineArg,outArg,fixtureFlag]=process.argv.slice(2);assert(moduleArg&&baselineArg&&outArg,'usage: actual-oracle.mjs ACTUAL_BST_MODULE CHECKED16_BST_MODULE NEW_OUT [--fixture]');const out=path.resolve(outArg);assert(!fs.existsSync(out));const build=fixtureFlag==='--fixture'?'p43.prefix.build':'p37.bst.build',insert=fixtureFlag==='--fixture'?'p43.prefix.insert':'p37.bst.insert',enc=n=>'$R_'+[...n].map(c=>c.charCodeAt(0)).join('_')+'$tree',sha=s=>createHash('sha256').update(s).digest('hex');
const parser=process.binding('natives')['internal/deps/acorn/acorn/dist/acorn'],pm={exports:{}};new Function('module','exports',parser)(pm,pm.exports);const parse=s=>pm.exports.parse(s,{ecmaVersion:'latest',sourceType:'module'});
function walk(n,f){if(!n||typeof n!=='object')return;f(n);for(const[k,v]of Object.entries(n))if(!['start','end'].includes(k)){if(Array.isArray(v))v.forEach(x=>walk(x,f));else if(v&&typeof v==='object')walk(v,f);}}
function instrument(s){const a=parse(s),edits=[],names=[];walk(a,n=>{if(n.type==='FunctionDeclaration'){const name=n.id.name;if(['apply','invokeExact','force','regionProofOpen'].includes(name)||name.startsWith('$R_')&&name.endsWith('$tree')){names.push(name);edits.push({at:n.body.start+1,text:`$p43Actual[${JSON.stringify(name)}]=($p43Actual[${JSON.stringify(name)}]??0)+1;`});}}});for(const e of edits.sort((a,b)=>b.at-a.at))s=s.slice(0,e.at)+e.text+s.slice(e.at);const workers=a.body.filter(n=>n.type==='FunctionDeclaration'&&[enc(build),enc(insert)].includes(n.id.name)).map(n=>n.id.name);s='const $p43Actual=Object.create(null);\n'+s+'\nfunction $p43ProofActive(){return regionProof!==null;}\nexport {$p43Actual,$p43ProofActive'+workers.map(x=>','+x).join('')+'};\n';parse(s);return{s,names,workers};}
fs.mkdirSync(out);const inputs=[];for(const[role,file]of[['candidate',moduleArg],['baseline',baselineArg]]){const source=fs.readFileSync(file,'utf8'),d=instrument(source),target=path.join(out,role+'.mjs');fs.writeFileSync(target,d.s,{flag:'wx'});inputs.push({role,path:fs.realpathSync(file),sha256:sha(source),diagnostic:target,diagnosticSha256:sha(d.s),workers:d.workers});}
fs.copyFileSync(import.meta.filename,path.join(out,'consumed-oracle.mjs'));fs.writeFileSync(path.join(out,'inputs.json'),JSON.stringify({inputs,build,insert,checkedSourceStatus:'parent supplied actual checked emission; verify separate receipt'},null,2)+'\n',{flag:'wx'});
const candidate=await import(pathToFileURL(inputs[0].diagnostic)),baseline=await import(pathToFileURL(inputs[1].diagnostic));const clear=m=>{for(const k of Object.keys(m.$p43Actual))delete m.$p43Actual[k]},counts=m=>({...m.$p43Actual}),results=[];
assert.equal(typeof candidate[enc(build)],'function','actual build worker emitted');assert.equal(typeof candidate[enc(insert)],'function','actual Nat wrapper emitted');
for(const[size,seed]of[[0,0],[1,0],[7,17],[32,0],[64,17],[16,0xffffffff]]){clear(candidate);clear(baseline);const expected=ref.inorder(ref.build(size,seed));assert.equal(candidate.default.bench(size,seed),expected);assert.equal(baseline.default.bench(size,seed),expected);assert.equal(candidate.$p43ProofActive(),false);assert((candidate.$p43Actual[enc(build)]??0)>0,'ordinary root actually executes build worker');if(size)assert((candidate.$p43Actual[enc(insert)]??0)>0,'ordinary root actually executes insert wrapper');if(size)assert(candidate.$p43Actual.apply<baseline.$p43Actual.apply,'executed generic reduction');results.push({size,seed,candidate:counts(candidate),baseline:counts(baseline)});}
function norm(t){const root={},todo=[[root,'v',t]];while(todo.length){const[p,k,t]=todo.pop();if(t.$==='BLeaf')p[k]={tag:'BLeaf'};else{assert.equal(t.$,'BNode');const n={tag:'BNode',v:t.a[1]};p[k]=n;todo.push([n,'r',t.a[2]],[n,'l',t.a[0]]);}}return root.v;}
function native(t){const root={},todo=[[root,'v',t]];while(todo.length){const[p,k,t]=todo.pop();if(t.tag==='BLeaf')p[k]={$:'BLeaf',a:[]};else{const n={$:'BNode',a:[]};p[k]=n;n.a[1]=t.v;todo.push([n.a,2,t.r],[n.a,0,t.l]);}}return root.v;}
for(const[fuel,x,tree]of[[0,2,ref.fromValues([5,2,8])],[1,2,ref.fromValues([5,2,8])],[9,5,ref.fromValues([5,5,5])]]){const expected=ref.insert(fuel,x,tree);assert.deepEqual(norm(candidate[enc(insert)](BigInt(fuel),x,native(tree))),expected);assert.deepEqual(norm(candidate.default[insert](BigInt(fuel),x,native(tree))),expected);}
const left={$:'BLeaf',a:[]},right={$:'BLeaf',a:[]},aliasTree={$:'BNode',a:[left,7,right]};const fresh=candidate[enc(insert)](0n,3,aliasTree);assert.notEqual(fresh,aliasTree);assert.equal(fresh.a[0],left);assert.equal(fresh.a[2],right);const changed=candidate[enc(insert)](1n,2,aliasTree);assert.equal(changed.a[2],right);assert.notEqual(changed.a[0].a[0],changed.a[0].a[2]);
for(const[n,s]of[[0,0],[7,17],[16,0xffffffff]])assert.deepEqual(norm(candidate[enc(build)](BigInt(n),BigInt(n+1),0,s,{$:'BLeaf',a:[]})),ref.build(n,s));
// Public/raw/data entry do not open ownership. Public fallback may still use its prior generic workers.
clear(candidate);candidate.default[build](3n,4n,0,17,{$:'BLeaf',a:[]});assert.equal(candidate.$p43Actual.regionProofOpen??0,0);assert.equal(candidate.$p43Actual[enc(build)]??0,0);
clear(candidate);const raw=candidate.G.bench.code([5,17]);candidate.call(raw,[]);assert.equal(candidate.$p43Actual.regionProofOpen??0,0);assert.equal(candidate.$p43Actual[enc(build)]??0,0);
clear(candidate);const partial=candidate.call(candidate.G.bench,[5]);assert.equal(candidate.$p43Actual.regionProofOpen??0,0);assert.equal(candidate.call(partial,[17]),ref.inorder(ref.build(5,17)));assert.equal(candidate.$p43ProofActive(),false);
// Mutable dependencies and native host replacement select original fallback.
for(const target of [build,'bst.down',insert]){const f=candidate.G[target],original=f.code;f.code=function(a){return original(a)};try{clear(candidate);assert.equal(candidate.default.bench(7,17),ref.inorder(ref.build(7,17)));assert.equal(candidate.$p43Actual[enc(build)]??0,0);}finally{f.code=original;}assert.equal(candidate.$p43ProofActive(),false);}
const imul=Math.imul;Math.imul=function(a,b){return imul(a,b)};try{clear(candidate);assert.equal(candidate.default.bench(7,17),ref.inorder(ref.build(7,17)));assert.equal(candidate.$p43Actual[enc(build)]??0,0);}finally{Math.imul=imul;}
const deep=native(ref.skew(12000,'right'));clear(candidate);const grown=candidate[enc(insert)](12001n,12001,deep);let at=grown,depth=0;while(at.$==='BNode'){depth++;at=at.a[2]}assert.equal(depth,12001);results.push({deepDepth:depth,counts:counts(candidate)});
if(fixtureFlag==='--fixture'){for(const[n,seed]of[[0,0],[7,17],[32,0xffffffff]]){let expected=seed;for(let i=0;i<n;i++)expected=(Math.imul(expected,3)+1)>>>0;assert.equal(candidate.default['p43.scalar.root'](n,seed),expected);assert.equal(candidate.default['p43.prefix.alloc.root'](n,seed),seed);}assert(!parse(fs.readFileSync(moduleArg,'utf8')).body.some(n=>n.type==='FunctionDeclaration'&&n.id.name===enc('p43.prefix.alloc')),'allocating helper alias refuses structural worker');}
const report={kind:'phase43-actual-products-oracle',passed:true,fixture:fixtureFlag==='--fixture',inputs,results};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(report));
