#!/usr/bin/env python3
"""Derive an unchecked exact-entry-state runtime and saved JS modules; never execute them."""
import argparse
import hashlib
import json
from pathlib import Path
import re

SELFHOST = Path(__file__).resolve().parents[3]
RUNTIME_SHA = 'e62cf92d8b600fdc2eb44029b1945f288c81bf878931f883a1b6f4fb5774aaeb'
CORE_SHA = '2276c6cf4be648421839a11e887913a1ac7fce7801e0ba9af86dc1b44fabd384'
API_SHA = '0d3325425139c59ac81c4f1bca19fa09e9f977062aa3b202c0ef1c8c7b56b0ea'
CHANGES = [(
    'let exactEntry=null,hasExactCodes=false;',
    'let $p45ExactCode=null,$p45ExactArgs=null,$p45ExactUsed=false,hasExactCodes=false;'
), (
    '''  const entry=exactEntry;
  const entered=entry!==null&&entry.code===code&&entry.args===a&&!entry.used;
  if(entered)entry.used=true;''',
    '''  const entered=$p45ExactCode!==null&&$p45ExactCode===code&&$p45ExactArgs===a&&!$p45ExactUsed;
  if(entered)$p45ExactUsed=true;'''
), (
    '''  const invoke=code.call,env=f.env,previous=exactEntry;
  exactEntry={code,args:all,used:false};
  try{return Reflect.apply(code,env,[all]);}
  finally{exactEntry=previous;}''',
    '''  const invoke=code.call,env=f.env;
  const $p45PreviousCode=$p45ExactCode,$p45PreviousArgs=$p45ExactArgs,$p45PreviousUsed=$p45ExactUsed;
  $p45ExactCode=code;$p45ExactArgs=all;$p45ExactUsed=false;
  try{return Reflect.apply(code,env,[all]);}
  finally{$p45ExactCode=$p45PreviousCode;$p45ExactArgs=$p45PreviousArgs;$p45ExactUsed=$p45PreviousUsed;}'''
)]


def require(condition, message):
    if not condition:
        raise ValueError(message)


def sha(data):
    return hashlib.sha256(data).hexdigest()


def identity(file):
    file = Path(file).resolve(strict=True)
    data = file.read_bytes()
    return dict(path=str(file), bytes=len(data), sha256=sha(data))


def save(file, value):
    with file.open('x') as stream:
        json.dump(value, stream, indent=2)
        stream.write('\n')


def derive(runtime):
    text = runtime.decode('utf-8')
    require('$p45Exact' not in text and '$p45Previous' not in text, 'Reserved runtime names')
    for before, after in CHANGES:
        require(text.count(before) == 1, 'Expected exactly one frozen replacement anchor')
        text = text.replace(before, after, 1)
    require(not re.search(r'\bexactEntry\b', text), 'Unmigrated exact-entry reference')
    return text.encode('utf-8')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--manifest', type=Path, required=True, help='Extracted checked04 candidate bundle')
    parser.add_argument('--runtime', type=Path, default=SELFHOST / 'src/runtime.mjs')
    parser.add_argument('--core', type=Path, default=SELFHOST / 'src/runtime/js/core.mjs')
    parser.add_argument('--out', type=Path, required=True, help='Fresh output directory')
    args = parser.parse_args()
    manifest_file = args.manifest.resolve(strict=True)
    inputs = [identity(p) for p in (__file__, manifest_file, args.runtime, args.core)]
    require(inputs[2]['sha256'] == RUNTIME_SHA and inputs[3]['sha256'] == CORE_SHA, 'Frozen runtime/core hashes')
    runtime, core = args.runtime.read_bytes(), args.core.read_bytes()
    require(runtime.startswith(b'// Generated by src/runtime/js/build.mjs; edit the fragments.\n' + core), 'Runtime/core prefix')
    changed = derive(runtime)
    manifest = json.loads(manifest_file.read_text())
    require(manifest.get('kind') == 'bend-program-bundle' and manifest.get('complete') is True, 'Complete source bundle')
    compiler = manifest['roles']['candidate']['compiler']
    require(compiler['kind'] == 'checked-development-attempt' and compiler['api']['sha256'] == API_SHA, 'Selected checked04 API')
    require(compiler['runtime']['sha256'] == RUNTIME_SHA, 'Selected runtime binding')
    rows = manifest['cases']
    require(0 < len(rows) <= 256 and len({r['id'] for r in rows}) == len(rows), 'Bounded unique cases')
    out = args.out.resolve()
    out.mkdir(parents=True, exist_ok=False)
    (out / 'modules').mkdir()
    (out / 'runtime.mjs').write_bytes(changed)
    (out / 'consumed-exact-state-v1.py').write_bytes(Path(__file__).read_bytes())
    report = dict(kind='phase45-saved-runtime-exact-state', complete=False, checked=False,
                  inputs=inputs, runtime=identity(out / 'runtime.mjs'), modules=[], replacements=[],
                  scope='Only private exact-entry token storage changes. Checked04 program suffixes remain byte-identical. No execution, conformance or performance claim.',
                  anchors=[dict(beforeSha256=sha(a.encode()), afterSha256=sha(b.encode())) for a, b in CHANGES])
    seen, total = {}, 0
    for row in rows:
        module = row['modules']['candidate']
        source = (manifest_file.parent / module['path']).resolve(strict=True)
        bound = identity(source)
        require(bound['sha256'] == module['sha256'] and bound['bytes'] == module['bytes'], 'Module identity mismatch')
        if source not in seen:
            data = source.read_bytes()
            total += len(data)
            require(0 < len(data) <= 64 * 1024**2 and total <= 512 * 1024**2, 'Module byte bounds')
            require(data.startswith(runtime), 'Exact frozen runtime prefix required')
            suffix = data[len(runtime):]
            require(b'$p45Exact' not in suffix and b'$p45Previous' not in suffix, 'Reserved module names')
            require(not re.search(rb'\bexactEntry\b', suffix), 'Program observes private old token')
            target = out / 'modules' / (str(len(seen)).zfill(2) + '-' + source.name)
            target.write_bytes(changed + suffix)
            report['modules'].append(dict(input=bound, output=identity(target), suffixSha256=sha(suffix)))
            inputs.append(bound)
            seen[source] = target
        report['replacements'].append(dict(id=row['id'], file=str(seen[source])))
    for item in inputs:
        require(identity(item['path']) == item, 'Consumed input changed during derivation')
    report['complete'] = True
    save(out / 'derive.json', report)
    replacements = [arg for row in report['replacements'] for arg in ('--replace', row['id'] + '=' + row['file'])]
    save(out / 'prototype-args.json', ['--from', str(manifest_file), *replacements])
    print(json.dumps(dict(complete=True, checked=False, cases=len(rows), modules=len(seen), out=str(out))))


if __name__ == '__main__':
    main()
