import assert from 'node:assert/strict';
const {default:D}=await import(process.env.BEND_DIAGNOSTIC_API||'../build/diagnostic/api.mjs');
const nil={$:'Nil'},list=xs=>xs.reduceRight((tail,head)=>({$:'Con',head,tail}),nil);
const t=(tag,name='',id=0,quant=0,kids=[])=>({$:'KTerm',tag,name,id,quant,kids:list(kids),removed:nil});
const ref=name=>t('Ref',name),adt=name=>t('ADT',name),typ=q=>t('Typ','',0,0,[t('Qua','',0,q)]),ctr=(name,...xs)=>t('Ctr',name,0,0,xs),all=(id,q,a,b,name='x')=>t('All',name,id,q,[a,b]),lam=(id,body,q=1,name='x')=>t('Lam',name,id,q,[body]),v=(id,name='x')=>t('Var',name,id),app=(f,x)=>t('App','',0,0,[f,x]);
const def=(name,typ,value=t('Absent'),kind='Def',ctors=[],arity=0)=>({$:'KDef',name,kind,arity,templates:0,typ,value,ctors:list(ctors),native:false,unsafe:false});
const bool=def('Bool',typ(2),t('Absent'),'ADT',[def('True',adt('Bool'),t('Absent'),'Ctr'),def('False',adt('Bool'),t('Absent'),'Ctr')]);
const text=text=>({$:'DText',text}),term=term=>({$:'DTerm',term}),span=(source,begin,end=begin)=>({$:'DSpan',source,begin,end}),noSpan={$:'DNoSpan'};
const report=(expected,observed=text(''),has_observed=true,context=[],definition='',location=noSpan,note='',trail=[])=>({$:'DDiagnostic',expected,observed,has_observed,context:list(context),definition,span:location,note,trail:list(trail)});
const origin=(definition,term,source,begin,end=begin,path=[])=>({$:'DOrigin',definition,term,source,begin,end,path:list(path)});
let count=0;function eq(name,a,b){assert.deepEqual(a,b,name);count++;console.log('PASS',name)}
eq('expected-observed layout',D.dg_render(nil,report(text('one'),text('two'))),'Error:\n- expected : one\n- observed : two');
eq('message-only layout',D.dg_render(nil,report(text('broken'),text(''),false)),'Error:\n- message  : broken');
eq('definition without span',D.dg_render(nil,report(text('x'),text('y'),true,[],'M.main')),'Error:\n- expected : x\n- observed : y\nLocation: M.main');
eq('first-line window',D.dg_render(nil,report(text('x'),text('y'),true,[],'',span('bad\nnext\nlast',0))),'Error:\n- expected : x\n- observed : y\nLocation:\n1>| bad\n2 | next');
eq('line-number width transition',D.dg_render(nil,report(text('x'),text('y'),true,[],'f',span('1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11',18))),'Error:\n- expected : x\n- observed : y\nLocation: f\n 9 | 9\n10>| 10\n11 | 11');
eq('trailing empty line',D.dg_render(nil,report(text('x'),text('y'),true,[],'',span('a\n',2))),'Error:\n- expected : x\n- observed : y\nLocation:\n1 | a\n2>| ');
eq('UTF16 offset with astral character',D.dg_render(nil,report(text('x'),text('y'),true,[],'',span('😀\nbad\nafter',3))),'Error:\n- expected : x\n- observed : y\nLocation:\n1 | 😀\n2>| bad\n3 | after');
eq('note follows location',D.dg_render(nil,report(text('x'),text('y'),true,[],'f',noSpan,'Hint: use a value.')),'Error:\n- expected : x\n- observed : y\nLocation: f\nHint: use a value.');
const ctx=[t('Bind','longer',12,1,[v(11,'A')]),t('Bind','A',11,0,[typ(1)])];
eq('aligned dependent context',D.dg_render(nil,report(term(v(11,'A')),term(v(12,'longer')),true,ctx)),'Error:\n- expected : A\n- observed : longer\nContext:\n- A      : Type\n- longer : A');
const shadows=[t('Bind','x',21,1,[adt('Bool')]),t('Bind','x',20,1,[adt('Bool')])];
eq('shadowed context indices',D.dg_render(nil,report(term(v(20)),term(v(21)),true,shadows)),'Error:\n- expected : x^0\n- observed : x\nContext:\n- x : Bool\n- x : Bool');
const alias=def('Alias',typ(1),adt('Bool'));
eq('expected terms normalize',D.dg_render(list([bool,alias]),report(term(ref('Alias')),term(typ(1)))),'Error:\n- expected : Bool\n- observed : Type');
const source='law main:\n  Bool\ndef main():\n  absent\n';const badRef=ref('absent'),book=list([bool,def('main',adt('Bool'),badRef)]);
const result=D.check_book_diagnostic(book,list([origin('main',badRef,source,source.indexOf('absent'))]));
eq('authoritative rejection preserved',result.error,D.check_book(book));
eq('actual undefined-reference source diagnostic',D.diagnostic_render(result),'Error:\n- expected : a defined name\n- observed : absent\nLocation: main\n3 | def main():\n4>|   absent\n5 | ');
eq('accepted program diagnostic remains empty',D.diagnostic_render(D.check_book_diagnostic(list([bool,def('main',adt('Bool'),ctr('True'))]),nil)),'');
const pair=def('Pair',typ(2),t('Absent'),'ADT',[def('Pair',all(30,1,adt('Bool'),all(31,1,adt('Bool'),adt('Pair'))),t('Absent'),'Ctr',[],2)]);
const duplicate=def('dup',all(33,1,adt('Bool'),adt('Pair')),lam(34,ctr('Pair',v(34),v(34))), 'Def',[],1);
eq('actual affine error payload',D.diagnostic_render(D.check_book_diagnostic(list([bool,pair,duplicate]),nil)),'Error:\n- expected : x\n- observed : x (consumed more than once)\nLocation: dup');
const mismatched=def('wrong',all(42,1,adt('Bool'),typ(1)),lam(43,v(43)),'Def',[],1);
eq('actual type mismatch captures context',D.diagnostic_render(D.check_book_diagnostic(list([bool,mismatched]),nil)),'Error:\n- expected : Type\n- observed : Bool\nContext:\n- x : Bool\nLocation: wrong');
const failedEquality=def('proof',t('Eql','',0,0,[ctr('True'),ctr('False'),adt('Bool')]),t('Rfl'));
eq('actual reflexivity endpoints',D.diagnostic_render(D.check_book_diagnostic(list([bool,failedEquality]),nil)),'Error:\n- expected : True{}\n- observed : False{}\nLocation: proof');
const loop=def('loop',all(51,1,adt('Bool'),adt('Bool')),lam(52,app(ref('loop'),v(52))),'Def',[],1);
eq('actual recursion error context',D.diagnostic_render(D.check_book_diagnostic(list([bool,loop]),nil)),'Error:\n- expected : a decreasing self-call (arguments are read left to right: each passed unchanged until one shrinks)\n- observed : loop\nContext:\n- x : Bool\nLocation: loop');
const ambiguous=D.check_book_diagnostic(book,list([origin('main',badRef,source,0),origin('main',badRef,source,10)]));
eq('ambiguous source is omitted',ambiguous.diagnostic.span,noSpan);
const elsewhere=D.check_book_diagnostic(book,list([origin('other',badRef,source,0)]));
eq('source lookup is definition-scoped',elsewhere.diagnostic.span,noSpan);
const incomplete=list([bool,def('claim',adt('Bool'))]);
eq('incomplete book preserves legacy diagnostic',D.diagnostic_render(D.check_book_diagnostic(incomplete,nil)),'Error: '+D.check_book(incomplete));
const duplicateBook=list([bool,def('main',adt('Bool'),ctr('True')),def('main',adt('Bool'),ctr('False'))]);
eq('declaration error preserves legacy diagnostic',D.diagnostic_render(D.check_book_diagnostic(duplicateBook,nil)),'Error: '+D.check_book(duplicateBook));
console.log(`${count} diagnostic tests passed`);
