// Run after assembling core/check modules and exporting check_book/check/infer.
const {default:K}=await import(process.env.BEND_KERNEL_API || '../build/kernel-test.mjs');
import assert from 'node:assert/strict';
const nil={$:'Nil'},list=(xs)=>xs.reduceRight((tail,head)=>({$:'Con',head,tail}),nil);
const t=(tag,name='',id=0,quant=0,kids=[],removed=[])=>({$:'KTerm',tag,name,id,quant,kids:list(kids),removed:list(removed)});
const qua=q=>t('Qua','',0,q),typ=q=>t('Typ','',0,0,[qua(q)]),v=(id)=>t('Var','x',id),all=(id,q,a,b)=>t('All','x',id,q,[a,b]),lam=(id,body,q=1)=>t('Lam','x',id,q,[body]),ref=n=>t('Ref',n),app=(f,x)=>t('App','',0,0,[f,x]),ctr=(n,...xs)=>t('Ctr',n,0,0,xs),adt=n=>t('ADT',n);
const d=(name,typ,value=t('Absent'),arity=0,kind='Def',ctors=[],native=false)=>({$:'KDef',name,kind,arity,templates:0,typ,value,ctors:list(ctors),native,unsafe:false});
const bool=d('Bool',typ(2),t('Absent'),0,'ADT',[d('True',adt('Bool'),t('Absent'),0,'Ctr'),d('False',adt('Bool'),t('Absent'),0,'Ctr')]);
const env=(book=[],name='',lhs=t('Absent'),pending=0,quantities=[])=>({$:'KEnv',book:list(book),name,lhs,pending,quantities:list(quantities),unsafe:false});
let total=0;function check(name,actual,expected){assert.equal(actual,expected,name);console.log('PASS',name);total++}
check('Bool declaration',K.check_book(list([bool])), '');
check('identity',K.check_book(list([bool,d('id',all(1,1,adt('Bool'),adt('Bool')),lam(2,v(2)),1)])), '');
check('undefined reference',K.check(env(),nil,ref('none'),1,typ(1)).error,'undefined name');
check('constructor wrong goal',K.check(env([bool]),nil,ctr('True'),1,typ(1)).error,'constructor requires a datatype goal');
check('good reflexivity',K.check(env([bool]),nil,t('Rfl'),1,t('Eql','',0,0,[ctr('True'),ctr('True'),adt('Bool')])).error,'');
check('bad reflexivity',K.check(env([bool]),nil,t('Rfl'),1,t('Eql','',0,0,[ctr('True'),ctr('False'),adt('Bool')])).error,'reflexivity endpoints differ');
const pair=d('Pair',typ(2),t('Absent'),0,'ADT',[d('Pair',all(10,1,adt('Bool'),all(11,1,adt('Bool'),adt('Pair'))),t('Absent'),2,'Ctr')]);
const dup=lam(20,ctr('Pair',v(20),v(20)));
check('affine duplication',K.check(env([bool,pair]),nil,dup,1,all(21,1,adt('Bool'),adt('Pair'))).error,'affine variable consumed more than allowed');
check('unrestricted duplication',K.check(env([bool,pair]),nil,lam(20,ctr('Pair',v(20),v(20)),2),1,all(21,2,adt('Bool'),adt('Pair'))).error,'');
const match=t('Mat','True',0,0,[ctr('False'),t('Mat','False',0,0,[ctr('True'),t('Efq')])]);
check('exhaustive match',K.check(env([bool]),nil,match,1,all(1,1,adt('Bool'),adt('Bool'))).error,'');
check('missing branch',K.check(env([bool]),nil,t('Mat','True',0,0,[ctr('False'),t('Efq')]),1,all(1,1,adt('Bool'),adt('Bool'))).error,'nonexhaustive match');
check('nondecreasing recursion',K.check_book(list([bool,d('loop',all(1,1,adt('Bool'),adt('Bool')),lam(2,app(ref('loop'),v(2))),1)])), 'loop: nondecreasing self-call');
const nat=d('Nat',typ(2),t('Absent'),0,'ADT',[d('Z',adt('Nat'),t('Absent'),0,'Ctr'),d('S',all(30,1,adt('Nat'),adt('Nat')),t('Absent'),1,'Ctr')]);
const walk=t('Mat','Z',0,0,[ctr('Z'),t('Mat','S',0,0,[lam(31,app(ref('walk'),v(31))),t('Efq')])]);
check('decreasing recursion',K.check_book(list([nat,d('walk',all(32,1,adt('Nat'),adt('Nat')),walk,1)])), '');
// The grade and constructor telescope use different binder IDs.
const box=d('Box',all(100,0,t('Qnt'),all(101,0,t('Typ','',0,0,[v(100)]),t('Typ','',0,0,[v(100)]))),t('Absent'),2,'ADT',[
 d('Box',all(102,0,t('Qnt'),all(103,0,t('Typ','',0,0,[v(102)]),all(104,1,v(103),t('ADT','Box',0,0,[v(102),v(103)])))),t('Absent'),1,'Ctr')]);
check('dependent grade datatype',K.check_book(list([box])), '');
const bind=(id,q,value)=>t('Bind','x',id,q,[value]);
const ann=(x,ty)=>t('Ann','',0,0,[x,ty]);
check('let type mismatch propagates',K.check(env([bool]),nil,t('Let','',0,0,[bind(110,1,ann(ctr('True'),adt('Bool'))),t('Qua','',0,1)]),1,adt('Bool')).error,'type mismatch');
check('let affine duplication',K.check(env([bool,pair]),nil,t('Let','',0,0,[bind(110,1,ann(ctr('True'),adt('Bool'))),ctr('Pair',v(110),v(110))]),1,adt('Pair')).error,'let binder consumed more than allowed');
check('erased runtime access',K.check(env([bool]),nil,lam(111,v(111)),1,all(112,0,adt('Bool'),adt('Bool'))).error,'affine variable consumed more than allowed');
const eqt=t('Eql','',0,0,[ctr('True'),ctr('True'),adt('Bool')]);
const motive=lam(120,lam(121,adt('Bool')));
const rewrite=t('Rwt','',0,0,[ann(t('Rfl'),eqt),motive,ctr('True')]);
check('J equality elimination',K.check(env([bool]),nil,rewrite,1,adt('Bool')).error,'');
const template=d('choose',all(130,0,adt('Bool'),adt('Bool')),lam(131,v(131)),1);template.templates=1;
check('template opaque value usage',K.check_book(list([bool,template])), '');
check('template closed call',K.check(env([bool,template]),nil,app(ref('choose'),ctr('True')),1,adt('Bool')).error,'');
check('template open call',K.check(env([bool,template]),list([t('Bind','x',132,1,[adt('Bool')])]),app(ref('choose'),v(132)),1,adt('Bool')).error,'template argument is open or ill-typed');
check('template bare reference',K.check(env([bool,template]),nil,ref('choose'),1,template.typ).error,'template requires all closed comptime arguments');
check('duplicate definition',K.check_book(list([bool,d('same',adt('Bool'),ctr('True')),d('same',adt('Bool'),ctr('False'))])), 'same: duplicate declaration');
check('law signature mismatch',K.check_book(list([bool,d('claim',adt('Bool')),d('claim',typ(1),adt('Bool'))])), 'claim: definition does not match prior law signature');
check('law signature fill',K.check_book(list([bool,d('claim',adt('Bool')),d('claim',adt('Bool'),ctr('True'))])), '');
const collision=d('AnotherBool',typ(2),t('Absent'),0,'ADT',[d('True',adt('AnotherBool'),t('Absent'),0,'Ctr')]);
check('constructor namespace uniqueness',K.check_book(list([bool,collision])), 'AnotherBool: duplicate constructor name');
check('open law final rejection',K.check_book(list([bool,d('ghost',adt('Bool'))])), '1 TODO found.\nThe code is incomplete, and not a valid proof yet.');
const annotatedMatcher=ann(match,all(145,1,adt('Bool'),adt('Bool')));
const betaMatcher=app(app(lam(146,annotatedMatcher),ctr('True')),ctr('True'));
check('beta retains matcher annotation',K.check(env([bool]),nil,betaMatcher,1,adt('Bool')).error,'');
check('beta constructor has contextual goal',K.check(env([bool]),nil,app(lam(147,v(147)),ctr('True')),1,adt('Bool')).error,'');
const io=d('IO',all(150,0,typ(1),typ(1)));io.native=true;
const foreign=d('foreign',app(ref('IO'),adt('Bool')),t('Foreign'));
check('foreign returning native IO',K.check_book(list([bool,io,foreign])), '');
check('foreign pure return rejected',K.check_book(list([bool,io,{...foreign,typ:adt('Bool')}])), 'foreign: foreign definition must return base IO directly');
const ioalias=d('Alias',io.typ,lam(151,app(ref('IO'),v(151))),1);
check('foreign IO alias rejected',K.check_book(list([bool,io,ioalias,{...foreign,typ:app(ref('Alias'),adt('Bool'))}])), 'foreign: foreign definition must return base IO directly');
const {default:A}=await import(process.env.BEND_ANNOTATE_API || '../build/annotate-test.mjs');
const annotated=A.annotate_book(list([bool,d('id',all(1,0,adt('Bool'),adt('Bool')),lam(2,ctr('True')),1)]));
const annotatedId=annotated.tail.head.value;
check('typed body annotation',annotatedId.tag,'Ann');
check('effective erased lambda quantity',annotatedId.kids.head.quant,0);
check('typed constructor child',annotatedId.kids.head.kids.head.tag,'Ann');
const poly=d('poly',all(160,0,typ(1),all(161,1,v(160),v(160))),lam(162,lam(163,v(163))),2);
const polyCall=app(app(ref('poly'),adt('Bool')),ctr('True'));
const polyMain=d('main',adt('Bool'),polyCall);
check('dependent annotation source checks',K.check_book(list([bool,poly,polyMain])),'');
const polyAnnotated=A.annotate_book(list([bool,poly,polyMain])).tail.tail.head.value;
check('dependent application result annotation',polyAnnotated.kids.tail.head.name,'Bool');
const polyFunction=polyAnnotated.kids.head.kids.head;
check('dependent application function annotation',polyFunction.kids.tail.head.tag,'All');
check('dependent application domain substitution',polyFunction.kids.tail.head.kids.head.name,'Bool');
const functionAlias=d('FunctionAlias',typ(1),all(170,1,adt('Bool'),adt('Bool')));
const aliasMain=d('aliasMain',ref('FunctionAlias'),ann(lam(171,v(171)),ref('FunctionAlias')),1);
check('annotated alias source checks',K.check_book(list([bool,functionAlias,aliasMain])),'');
const aliasAnnotated=A.annotate_book(list([bool,functionAlias,aliasMain])).tail.tail.head.value;
check('annotated alias lambda quantity',aliasAnnotated.kids.head.quant,1);
check('annotated alias binder type',aliasAnnotated.kids.head.kids.head.kids.tail.head.name,'Bool');
const unsafeFn=all(180,2,all(181,1,adt('Bool'),adt('Bool')),adt('Bool'));
const unsafeLaw=d('unsafeLaw',all(182,1,unsafeFn,adt('Bool')));
const unsafeFill={...unsafeLaw,value:lam(183,app(v(183),lam(184,v(184)))),unsafe:true};
check('unsafe fill governs prior signature kind',K.check_book(list([bool,unsafeLaw,unsafeFill])),'');
check('safe fill retains Data domain wall',K.check_book(list([bool,unsafeLaw,{...unsafeFill,unsafe:false}])),'unsafeLaw: type mismatch');
console.log(total+' passed');
