// Export specialize_book/check_book/wnf from core/check modules to build/specialize-test.mjs.
import {pathToFileURL} from 'node:url';
const {default:K}=await import(process.env.BEND_TEMPLATE_API?pathToFileURL(process.env.BEND_TEMPLATE_API).href:new URL('../build/specialize-test.mjs',import.meta.url).href);
import assert from 'node:assert/strict';
const nil={$:'Nil'},list=xs=>xs.reduceRight((tail,head)=>({$:'Con',head,tail}),nil),arr=xs=>xs.$==='Nil'?[]:[xs.head,...arr(xs.tail)];
const t=(tag,name='',id=0,quant=0,kids=[],removed=[])=>({$:'KTerm',tag,name,id,quant,kids:list(kids),removed:list(removed)});
const qua=q=>t('Qua','',0,q),typ=q=>t('Typ','',0,0,[qua(q)]),v=id=>t('Var','x',id),all=(id,q,a,b)=>t('All','x',id,q,[a,b]),lam=(id,b,q=1)=>t('Lam','x',id,q,[b]),ref=n=>t('Ref',n),app=(f,x)=>t('App','',0,0,[f,x]),ctr=(n,...xs)=>t('Ctr',n,0,0,xs),adt=n=>t('ADT',n);
const d=(name,typ,value=t('Absent'),arity=0,kind='Def',ctors=[],native=false,templates=0)=>({$:'KDef',name,kind,arity,templates,typ,value,ctors:list(ctors),native,unsafe:false});
const bool=d('Bool',typ(2),t('Absent'),0,'ADT',[d('True',adt('Bool'),t('Absent'),0,'Ctr'),d('False',adt('Bool'),t('Absent'),0,'Ctr')]);
const template=d('choose',all(130,0,adt('Bool'),adt('Bool')),lam(131,v(131)),1,'Def',[],false,1);
const source=[bool,template,d('a',adt('Bool'),app(ref('choose'),ctr('True'))),d('b',adt('Bool'),app(ref('choose'),ctr('True'))),d('c',adt('Bool'),app(ref('choose'),ctr('False')))];
assert.equal(K.check_book(list(source)),'');
const r=K.specialize_book(list(source));
assert.equal(r.error,'');
const ds=arr(r.book);
assert.equal(ds.filter(x=>x.name.startsWith('choose~')).length,2);
assert.equal(ds.find(x=>x.name==='a').value.name,ds.find(x=>x.name==='b').value.name);
assert.notEqual(ds.find(x=>x.name==='a').value.name,ds.find(x=>x.name==='c').value.name);
assert.equal(K.wnf(r.book,ref('a')).name,'True');assert.equal(K.wnf(r.book,ref('c')).name,'False');
console.log('PASS specialization, memoization, different keys, normalization');
const nat=d('Nat',typ(2),t('Absent'),0,'ADT',[d('Z',adt('Nat'),t('Absent'),0,'Ctr'),d('S',all(200,1,adt('Nat'),adt('Nat')),t('Absent'),1,'Ctr')]);
const walkBody=t('Mat','Z',0,0,[ctr('Z'),t('Mat','S',0,0,[lam(203,app(app(ref('walk'),v(202)),v(203))),t('Efq')])]);
const walk=d('walk',all(200,0,adt('Bool'),all(201,1,adt('Nat'),adt('Nat'))),lam(202,walkBody,0),2,'Def',[],false,1);
const sw=[bool,nat,walk,d('run',adt('Nat'),app(app(ref('walk'),ctr('True')),ctr('S',ctr('Z'))))];
assert.equal(K.check_book(list(sw)),'');
const wr=K.specialize_book(list(sw));assert.equal(wr.error,'');assert.equal(K.wnf(wr.book,ref('run')).name,'Z');
console.log('PASS decreasing specialized recursion');
const erased=d('ignore',all(300,0,adt('Bool'),adt('Bool')),lam(301,ctr('True'),0),1);
const openErased=d('dead',all(302,1,adt('Bool'),adt('Bool')),lam(303,app(ref('ignore'),app(ref('choose'),v(303)))),1);
const er=[bool,template,erased,openErased];assert.equal(K.check_book(list(er)),'');
const e=K.specialize_book(list(er));assert.equal(e.error,'');assert.equal(arr(e.book).filter(x=>x.name.startsWith('choose~')).length,0);console.log('PASS erased open template retained');
const bare=K.specialize_book(list([bool,template,d('bad',template.typ,ref('choose'))]));assert.match(bare.error,/all closed/);console.log('PASS underapplied template rejected');
const depthBook=[bool];for(let i=0;i<65;i++)depthBook.push(d('f'+i,all(1000+i*2,0,adt('Bool'),adt('Bool')),lam(1001+i*2,i?app(ref('f'+(i-1)),v(1001+i*2)):v(1001+i*2),0),1,'Def',[],false,1));depthBook.push(d('deep',adt('Bool'),app(ref('f64'),ctr('True'))));
assert.equal(K.check_book(list(depthBook)),'');const deep=K.specialize_book(list(depthBook));assert.match(deep.error,/64 levels/);console.log('PASS depth guard');
let huge=ctr('True');for(let i=0;i<1400;i++)huge=t('Ann','',0,0,[huge,adt('Bool')]);
const growth=K.specialize_book(list([bool,template,d('huge',adt('Bool'),app(ref('choose'),huge))]));assert.match(growth.error,/growing/);console.log('PASS key growth guard');
