#!/usr/bin/env python3
"""Read retained C only; never invoke a compiler or toolchain."""
import collections,hashlib,json,pathlib,re
ROOT=pathlib.Path(__file__).resolve().parents[2];BASE=ROOT/'selfhost/build/phase5/final-backends/broad-run-01/paired';OUT=pathlib.Path(__file__).with_suffix('.json');sha=lambda b:hashlib.sha256(b).hexdigest();result={'kind':'phase6-static-native-arity-wall-footprint','compilerExecuted':False,'variants':{}}
sectionText={}
for n in ['reference','candidate']:
 p=BASE/(n+'.json.artifacts/1520/program.c');data=p.read_bytes();s=data.decode();marks=list(re.finditer(r'^// ([^\n]+)\n// =+\n',s,re.M));sections={m[1]:s[m.start():marks[i+1].start() if i+1<len(marks) else len(s)]for i,m in enumerate(marks)};sectionText[n]=sections;seg=sections['Segments'];ms=list(re.finditer(r'^  WL_CASE\(([^\n]+)\)\n',seg,re.M));ss=[(m[1],seg[m.start():ms[i+1].start() if i+1<len(ms) else len(seg)])for i,m in enumerate(ms)];ones=[(k,v)for k,v in ss if 'r0 = 1ull;\n    WL_RETN(1);'in v];sig=re.search(r'^#define WL_SIG (.*)$',s,re.M)[1]
 result['variants'][n]={'file':str(p),'bytes':len(data),'sha256':sha(data),'lines':len(s.splitlines()),'sections':{k:{'bytes':len(v.encode()),'sha256':sha(v.encode())}for k,v in sections.items()},'wlCaseCount':len(ss),'fidArityEntries':len(re.search(r'\bFID_ARITY_T\[\] = \{([^}]+)',s)[1].split(',')),'cidArityEntries':len(re.search(r'\bCID_ARITY_T\[\] = \{([^}]+)',s)[1].split(',')),'termRegistersInSignature':len(re.findall(r'\bTerm r\w*',sig)),'segmentTokenOccurrences':{x:seg.count(x)for x in ['e.mem[','STK(','heap_alloc','task_node','WL_ROOM','WL_JMP','term_clo']},'largestSegments':[{'name':k,'bytes':len(v.encode()),'memoryOccurrences':v.count('e.mem['),'stackOccurrences':v.count('STK(')}for k,v in sorted(ss,key=lambda x:len(x[1]),reverse=True)[:10]],'syntacticReturnLiteralOne':{'segments':len(ones),'bytes':sum(len(v.encode())for k,v in ones),'memoryOccurrences':sum(v.count('e.mem[')for k,v in ones),'stackOccurrences':sum(v.count('STK(')for k,v in ones)}}
a,b=sectionText['reference'],sectionText['candidate'];same=[k for k in a if a[k]==b[k]];result['identicalMarkedSections']={'names':same,'bytesPerVariant':sum(len(a[k].encode())for k in same)};result['changedMarkedSections']=[k for k in a if a[k]!=b[k]];result['reviewedEmitterSources']=[]
for n in ['bridge','emit','tables','book','direct']:
 p=ROOT/'selfhost/build/phase5/integration/attempt-05/snapshot/src/back/native'/f'{n}.bend';data=p.read_bytes();result['reviewedEmitterSources'].append({'file':str(p),'sha256':sha(data)})
OUT.write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({'bytes':[v['bytes']for v in result['variants'].values()],'common':result['identicalMarkedSections'],'changed':result['changedMarkedSections']}))
