// Exact differential gates for native telescope erasure and annotated contexts.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {pathToFileURL} from 'node:url';
const [oldArg,newArg,outArg]=process.argv.slice(2);if(!outArg)throw Error('usage: native-context.test.mjs BASELINE_API CANDIDATE_API NEW_OUTPUT_DIRECTORY [--measure]');
const baseline=fs.realpathSync(oldArg),candidate=fs.realpathSync(newArg),output=path.resolve(outArg);fs.mkdirSync(output,{recursive:false});const project=path.resolve(import.meta.dirname,'../../..'),runtime=path.join(project,'src/runtime/native/runtime.c'),hash=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex'),digest=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
const identities=Object.fromEntries([import.meta.filename,process.execPath,baseline,candidate,runtime].map(p=>[p,hash(p)]));
const helpers={nc_tele_fill:3,nc_live_count:3,nc_erase_args:3,nc_context_defs:2,nc_annotated_context:2,nc_compile:3,book_cached:2,annotate_selected:3,annotate_book:1,check_book:1,f_load_graph:2,nc_annotation_stops:1,reach_book:3,specialize_book:1,specialized_book:1,specialized_error:1,driver_owned:1,driver_emit_owned:1,driver_todos:1};
async function expose(file,label,counted=false){let source=fs.readFileSync(file,'utf8');const counts=['wnf','lookup','index_lookup'];if(counted){for(const n of counts){const re=new RegExp('function \\$'+n+'\\$\\([^)]*\\) \\{');assert.ok(re.test(source),n);source=source.replace(re,m=>m+'operationCounts['+JSON.stringify(n)+']++;');}source='const operationCounts='+JSON.stringify(Object.fromEntries(counts.map(n=>[n,0])))+';\n'+source;}const entries=Object.entries(helpers).map(([n,a])=>{assert.equal(source.split('function $'+n+'$(').length,2,n);return JSON.stringify(n)+':run_lib($'+n+'$,'+a+')'}),copy=path.join(output,label+'.mjs');fs.writeFileSync(copy,source+'\nexport const nativeProbe={'+entries.join(',')+'};\n'+(counted?'export {operationCounts};\n':''));const module=await import(pathToFileURL(copy));return {api:module.nativeProbe,counts:module.operationCounts,file:copy,sha256:hash(copy)};}
const old=await expose(baseline,'baseline'),next=await expose(candidate,'candidate');
const nil={$:'Nil'},list=xs=>xs.reduceRight((tail,head)=>({$:'Con',head,tail}),nil),t=(tag,name='',id=0,quant=0,kids=[])=>({$:'KTerm',tag,name,id,quant,kids:list(kids),removed:nil}),typ=q=>t('Typ','',0,0,[t('Qua','',0,q)]),v=id=>t('Var','x',id),all=(id,q,a,b)=>t('All','x',id,q,[a,b]),ref=n=>t('Ref',n),adt=n=>t('ADT',n),ann=(x,ty)=>t('Ann','',0,0,[x,ty]),ctr=n=>t('Ctr',n);
const d=(name,type,value=t('Absent'),kind='Def',ctors=[])=>({$:'KDef',name,kind,arity:0,templates:0,typ:type,value,ctors:list(ctors),native:false,unsafe:false}),bool=d('B',typ(2),t('Absent'),'ADT',[d('Yes',adt('B'),t('Absent'),'Ctr'),d('No',adt('B'),t('Absent'),'Ctr')]);
const report={kind:'phase3-native-context-erasure-differential',started:new Date().toISOString(),node:process.version,nodeArgs:process.execArgv,identities,exposures:[old,next].map(({file,sha256})=>({file,sha256})),cases:[],nativeSources:[],complete:false};const save=()=>fs.writeFileSync(output+'/report.json',JSON.stringify(report,null,2)+'\n');save();
function compare(name,method,args){const expected=old.api[method](...args),actual=next.api[method](...args);assert.deepEqual(actual,expected,name);report.cases.push({name,method,inputSha256:digest(args),outputSha256:digest(expected),exact:true});save();}
for(let count=0;count<=16;count++){let tel=adt('B');for(let i=count-1;i>=0;i--)tel=all(100+i,i%3,adt('B'),tel);const book=list([bool,d('Tel',typ(1),tel),d('Alias',typ(1),ref('Tel'))]),args=list(Array.from({length:count},(_,i)=>ann(ctr(i%2?'Yes':'No'),adt('B'))));for(const head of [tel,ref('Tel'),ref('Alias')]){compare('fill '+count+' '+head.tag+' '+head.name,'nc_tele_fill',[book,head,args]);compare('live '+count+' '+head.tag+' '+head.name,'nc_live_count',[book,head,count]);compare('erase '+count+' '+head.tag+' '+head.name,'nc_erase_args',[book,head,args]);}}
const dependent=all(800,0,typ(1),all(801,1,v(800),v(800))),depBook=list([bool,d('Dep',typ(1),dependent)]),depArgs=list([adt('B'),ann(ctr('Yes'),adt('B'))]);compare('dependent substitution fill','nc_tele_fill',[depBook,ref('Dep'),depArgs]);compare('dependent erased type and live value','nc_erase_args',[depBook,ref('Dep'),depArgs]);
const a=d('a',adt('B'),ctr('Yes')),b=d('b',adt('B'),ctr('No')),replacement={...a,value:ann(ctr('No'),adt('B'))},absent={...a,kind:'Absent'},empty={...a,name:''};
for(const [name,book,annotated] of [
 ['empty',nil,nil],['no selection',list([a,b]),nil],['replace',list([a,b]),list([replacement])],['first duplicate wins',list([a,b,a]),list([replacement,a])],['Absent shadows later replacement',list([a]),list([absent,replacement])],['empty names',list([empty]),list([{...empty,value:ctr('No')},empty])],['cached book',old.api.book_cached(list([a,b]),123),list([replacement])],['cached annotations',list([a,b]),old.api.book_cached(list([replacement]),99)],
 ['cache after raw prefix',list([a,b]),{$:'Con',head:b,tail:old.api.book_cached(list([replacement]),99)}],
 ['reserved sentinel name after raw prefix',list([{...a,name:'$kernel.cache'}]),{$:'Con',head:b,tail:old.api.book_cached(list([replacement]),99)}]
])compare('context '+name,'nc_annotated_context',[book,annotated]);
const prefix='type B is Data:\n  Yes{}\n  No{}\n';const fixtures=[['identity',prefix+'def id(x: B) -> B:\n  x\ndef main() -> B:\n  id(Yes{})\n'],['dependent',prefix+'law poly:\n  for -A: Type\n  for x: A\n  A\ndef poly(A, x):\n  x\ndef main() -> B:\n  poly(B, Yes{})\n'],['mixed-fields',prefix+'type Box is Data:\n  Box{left: B, right: B}\ndef first(x: Box) -> B:\n  match x:\n    case Box{a, b}:\n      a\ndef main() -> B:\n  first(Box{Yes{}, No{}})\n']];
for(const [name,text] of fixtures){const file=path.join(output,name+'.bend');fs.writeFileSync(file,text);const sources=list([{$:'FSource',name:file,path:file,text}]),loaded=old.api.f_load_graph(file,sources);assert.equal(loaded.error,'');const book=loaded.book;for(const a of [old,next]){assert.equal(a.api.check_book(book),'');assert.equal(a.api.driver_owned(book),'');assert.equal(a.api.driver_todos(book),0);}const s=old.api.specialize_book(book);assert.equal(old.api.specialized_error(s),'');const final=old.api.specialized_book(s);assert.equal(old.api.driver_emit_owned(final),'');const stops=old.api.nc_annotation_stops(final),selected=old.api.reach_book(final,list(['main']),stops),annotated=old.api.annotate_selected(final,selected,stops);assert.deepEqual(next.api.annotate_selected(final,selected,stops),annotated);const contexts=[old.api.nc_annotated_context(final,annotated),next.api.nc_annotated_context(final,annotated)];assert.deepEqual(contexts[0],contexts[1]);const c=[old.api.nc_compile(contexts[0],fs.readFileSync(runtime,'utf8'),''),next.api.nc_compile(contexts[1],fs.readFileSync(runtime,'utf8'),'')];assert.equal(c[0].error,'');assert.deepEqual(c[1],c[0],name+' exact native C');fs.writeFileSync(output+'/'+name+'.c',c[0].source);report.nativeSources.push({name,checked:true,sourceSha256:hash(file),annotationSha256:digest(annotated),nativeBytes:Buffer.byteLength(c[0].source),nativeSha256:hash(output+'/'+name+'.c'),exact:true});save();}
if(process.argv.includes('--measure')){const variants=[['baseline',await expose(baseline,'baseline-counted',true)],['candidate',await expose(candidate,'candidate-counted',true)]];report.operations=[];let tel=adt('B');for(let i=15;i>=0;i--)tel=all(100+i,i%3,adt('B'),tel);const book=list([bool,d('Tel',typ(1),tel)]),args=list(Array.from({length:16},()=>ann(ctr('Yes'),adt('B'))));for(const [method,values] of [['nc_tele_fill',[book,ref('Tel'),args]],['nc_live_count',[book,ref('Tel'),16]],['nc_erase_args',[book,ref('Tel'),args]]]){const row={method,counts:{}};for(const [name,a] of variants){Object.keys(a.counts).forEach(k=>a.counts[k]=0);assert.deepEqual(a.api[method](...values),old.api[method](...values));row.counts[name]={...a.counts};}report.operations.push(row);}
 report.contextMeasurements=[];for(const size of [64,256,1024]){const book=list(Array.from({length:size},(_,i)=>d('entry'+i,adt('B'),ctr('Yes')))),annotated=list(Array.from({length:size},(_,i)=>d('entry'+(size-i-1),adt('B'),ann(ctr('No'),adt('B'))))),row={size,counts:{},samples:[]},expected=old.api.nc_annotated_context(book,annotated);for(const [name,a] of variants){Object.keys(a.counts).forEach(k=>a.counts[k]=0);assert.deepEqual(a.api.nc_annotated_context(book,annotated),expected);row.counts[name]={...a.counts};}for(let rep=0;rep<3;rep++)for(const [name,a] of (rep%2?[['candidate',next],['baseline',old]]:[['baseline',old],['candidate',next]])){const start=performance.now(),value=a.api.nc_annotated_context(book,annotated),milliseconds=performance.now()-start;assert.deepEqual(value,expected);row.samples.push({variant:name,rep,milliseconds});}const median=xs=>xs.sort((a,b)=>a-b)[1];row.medians=Object.fromEntries(['baseline','candidate'].map(n=>[n,median(row.samples.filter(r=>r.variant===n).map(r=>r.milliseconds))]));report.contextMeasurements.push(row);save();}}
report.inputsUnchanged=Object.entries(identities).every(([p,h])=>hash(p)===h);assert.equal(report.inputsUnchanged,true);report.complete=true;report.finished=new Date().toISOString();save();console.log(JSON.stringify({complete:true,cases:report.cases.length,nativeSources:report.nativeSources.length,operations:report.operations,contextMeasurements:report.contextMeasurements?.map(x=>({size:x.size,medians:x.medians,counts:x.counts}))}));
