// Concatenate primitive runtime fragments for embedding in standalone output.
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'../..');
const parts=['core','base','effects','readback','foreign'];
const source='// Generated by src/runtime/js/build.mjs; edit the fragments.\n'+parts.map(n=>fs.readFileSync(path.join(import.meta.dirname,n+'.mjs'),'utf8')).join('\n');
fs.writeFileSync(path.join(root,'runtime.mjs'),source);
