// Read-only pinned TypeScript parse/check diagnostic; never runs/emits the program.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';import {inspect} from 'node:util';
const[upArg,inputArg,outArg]=process.argv.slice(2);assert(upArg&&inputArg&&outArg,'usage: diagnose.mjs PINNED_UPSTREAM SOURCE NEW_REPORT.json');
const up=fs.realpathSync(upArg),input=fs.realpathSync(inputArg),out=path.resolve(outArg);assert(!fs.existsSync(out));
const sha=x=>createHash('sha256').update(x).digest('hex'),identity=p=>({path:fs.realpathSync(p),sha256:sha(fs.readFileSync(p))});
const git=(...args)=>execFileSync('git',['-C',up,...args],{encoding:'utf8'}).trim(),pin='018751270e800bc222a93dad7f257083ee53a5f7';assert.equal(git('rev-parse','HEAD'),pin);assert.equal(git('diff','--name-only','HEAD','--','bend2/bend.ts','bend2/base.bend'),'');
const sources=['bend2/bend.ts','bend2/base.bend'].map(n=>identity(path.join(up,n))),inputIdentity=identity(input),report={kind:'phase42-pinned-ts-diagnostic',complete:false,pass:false,checked:false,producer:identity(import.meta.filename),upstreamCommit:pin,sources,input:inputIdentity,node:process.version};
let phase='load',B;const begin=performance.now();
try{B=await import(pathToFileURL(path.join(up,'bend2/bend.ts')));const book=B.book_nil();phase='parse';await B.book_load(book,input,'',new Map());report.parsed=true;report.holes=book.hols;report.definitions=Object.keys(book.tlds).length;phase='check';B.book_valid(book);assert.equal(book.hols,0);report.checked=true;report.pass=true;}
catch(error){let formatted;try{formatted=error?.$==='Err'&&B?.err_show?B.err_show(error):error?.stack??String(error);}catch(formatError){report.formatError=formatError.stack??String(formatError);formatted=inspect(error,{depth:2,maxArrayLength:12,maxStringLength:2000});}
 report.error={phase,tag:error?.$,name:error?.name,message:error?.message,formatted,keys:error&&typeof error==='object'?Object.keys(error):[],primitive:typeof error==='object'?undefined:String(error)};process.exitCode=1;}
for(const row of[...sources,inputIdentity])assert.equal(identity(row.path).sha256,row.sha256,'diagnostic input changed');assert.equal(git('rev-parse','HEAD'),pin);report.complete=true;report.elapsedMs=performance.now()-begin;fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(report.error?.formatted??JSON.stringify({complete:true,parsed:report.parsed,checked:report.checked,holes:report.holes}));
