import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
import {identity,verifyIdentity,validatedCache} from '../../development/workflow.mjs';import {verifyEqualityDerivation} from '../../development/equality.mjs';import {supervise,requireExecution} from '../../development/process.mjs';
const read=f=>JSON.parse(fs.readFileSync(f)),write=(f,v)=>fs.writeFileSync(f,JSON.stringify(v,null,2)+'\n',{flag:'wx'});
const [mode,directory,source,resultFile]=process.argv.slice(2),out=path.resolve(directory),configFile=path.join(out,'config.json');
if(mode==='worker'){
 const c=read(configFile);c.inputs.forEach(verifyIdentity);const D=await import(pathToFileURL(c.driver));const start=performance.now(),r=await D.inspect(source,{mode:'native',withReport:true});const requestMs=performance.now()-start;const {code,...rest}=r;let emitted=null;if(typeof code==='string'){const f=resultFile+'.c';fs.writeFileSync(f,code,{flag:'wx'});emitted=identity(f);emitted.bytes=Buffer.byteLength(code);}c.inputs.forEach(verifyIdentity);write(resultFile,{...rest,emitted,requestMs,files:(r.files||[]).map(identity),inputsVerified:true,scope:'Checked emission only; no Clang or program execution.'});assert.equal(r.status,'ok');assert.equal(r.checked,true);assert.equal(r.phase,'compile');assert.ok(emitted);
}else if(mode==='run'){
 const start=performance.now(),s=read(path.resolve('build/phase5/final-backends/broad-snapshot-04/snapshot.json'));s.inputs.forEach(verifyIdentity);verifyEqualityDerivation(s.derivation.file);
 const driver=path.join(path.dirname(s.target),'../typed-driver.mjs'),project=path.dirname(path.dirname(driver)),original=path.resolve('.bootstrap/upstream/tests/reg/arity_wall.bend'),text=fs.readFileSync(original,'utf8'),cases=[];
 for(const n of [32,64,128]){let t=text;const fields=Array.from({length:n},(_,i)=>'f'+i);t=t.replace(/^  MkR255\{.*\}$/m,'  MkR255{'+fields.map(f=>f+': U32').join(', ')+'}').replace(/^    case MkR255\{.*\}:$/m,'    case MkR255{'+fields.join(', ')+'}:').replace(/^  pick\(MkR255\{.*\}\)$/m,'  pick(MkR255{'+fields.map(()=>1).join(', ')+'})');assert.notEqual(t,text);t=t.replaceAll('R255','R'+n);const f=path.join(out,'fields-'+n+'.bend');fs.writeFileSync(f,t,{flag:'wx'});cases.push({n,source:identity(f)});}
 const cache=validatedCache(path.join(project,'build/typed/cache'),s.api.file,s.base.file);const inputs=[identity(import.meta.filename),identity(path.join(out,'preregistration.json')),identity(original),s.api,s.checkedParent,s.bootstrap,s.derivation,s.runtime,s.base,identity(process.execPath),identity(cache.file),...cases.map(x=>x.source),...['typed-driver','native-build','compiler-abi','assemble','node-resource-args'].map(n=>identity(path.join(project,'tools',n+'.mjs'))),...['workflow','process','equality'].map(n=>identity(new URL('../../development/'+n+'.mjs',import.meta.url).pathname)),identity(path.join(project,'src/runtime/native/runtime.c')),identity(path.join(path.dirname(s.base.file),'effs/print.c'))];
 const config={driver,api:s.api,base:s.base,runtime:s.runtime,inputs,cases};write(configFile,config);const env={...process.env};for(const k of Object.keys(env))if(k.startsWith('BEND_')||k==='NODE_OPTIONS')delete env[k];Object.assign(env,{BEND_TYPED_API:s.api.file,BEND_TYPED_RUNTIME:s.runtime.file,BEND_BASE:s.base.file,BEND_TYPED_TRACE:'1'});
 const r={kind:'phase6-native-scalar-field-scaling',complete:false,started:new Date().toISOString(),checkedArtifact:s.api,checkedParent:s.checkedParent,derivation:s.derivation,newBootstrap:false,inputs,rows:[],scope:'Emit-only source/size scaling; no Clang, runtime parity or isolated speed claim.'};const save=()=>fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(r,null,2)+'\n');save();
 try{for(const c of cases){const result=path.join(out,'fields-'+c.n+'.json'),remaining=300000-(performance.now()-start);assert.ok(remaining>0);const e=await supervise('taskset',['-c','1',process.execPath,'--stack-size=4096','--max-old-space-size=4096',import.meta.filename,'worker',out,c.source.file,result],{directory:path.join(out,'process-'+c.n),env,timeoutMs:Math.min(90000,Math.floor(remaining))});const row={n:c.n,source:c.source,execution:e,result:fs.existsSync(result)?read(result):null};r.rows.push(row);save();requireExecution(e);assert.equal(row.result.status,'ok');assert.equal(row.result.checked,true);assert.equal(row.result.inputsVerified,true);}
 inputs.forEach(verifyIdentity);verifyEqualityDerivation(s.derivation.file);r.inputsVerified=true;r.complete=true;r.finished=new Date().toISOString();save();}catch(error){r.error=String(error.stack??error);r.finished=new Date().toISOString();save();throw error;}
}else throw Error('Usage: native-scaling.mjs run DIRECTORY | worker DIRECTORY SOURCE RESULT');
