// Fresh single-API workers avoid retaining two compiler graphs across large samples.
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {spawn} from 'node:child_process';
const sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),save=(f,j)=>fs.writeFileSync(f,JSON.stringify(j,null,2)+'\n');
if(process.argv[2]==='--worker'){
 const request=JSON.parse(fs.readFileSync(process.argv[3]));for(const [f,h] of Object.entries(request.inputs))assert.equal(sha(f),h,'Input drift before worker: '+f);
 process.env.BEND_TYPED_API=request.api;process.env.BEND_TYPED_RUNTIME=request.runtime;process.env.BEND_BASE=request.base;
 const D=await import(pathToFileURL(request.host)),api=await D.loadApi();const cache=await D.prepareBase(api),phases=[];
 const wrapped=Object.fromEntries(Object.entries(api).map(([name,method])=>[name,(...args)=>{const start=performance.now();try{return method(...args);}finally{phases.push({name,milliseconds:performance.now()-start});}}]));
 const start=performance.now(),result=await D.inspect(request.input,{mode:request.mode??'compile',api:wrapped}),compileMs=performance.now()-start;
 assert.equal(result.status,'ok',JSON.stringify(result));assert.equal(result.checked,true);fs.writeFileSync(request.output,result.code);
 for(const [f,h] of Object.entries(request.inputs))assert.equal(sha(f),h,'Input drift during worker: '+f);
 save(request.result,{kind:'phase4-analysis-fresh-worker',complete:true,api:request.api,compileMs,phases,outputSha256:sha(request.output),outputBytes:Buffer.byteLength(result.code),baseCache:{compilerSha256:cache.compilerSha256,baseSha256:cache.baseSha256,bookSha256:cache.bookSha256},inputsUnchanged:true,node:process.version,nodeArgs:process.execArgv,maxRssKiB:process.resourceUsage().maxRSS});
}else{
 const [configArg,outArg]=process.argv.slice(2);if(!outArg)throw Error('usage: analysis-fresh.mjs CONFIG.json NEW_DIRECTORY');const config=JSON.parse(fs.readFileSync(configArg)),resolve=f=>fs.realpathSync(path.resolve(path.dirname(path.resolve(configArg)),f)),out=path.resolve(outArg);fs.mkdirSync(out,{recursive:false});
 const files=Object.fromEntries(['baseline','candidate','host','runtime','base','input'].map(k=>[k,resolve(config[k])])),inputs=Object.fromEntries([...Object.values(files),import.meta.filename,configArg].map(f=>[fs.realpathSync(f),sha(f)]));
 const report={kind:'phase4-analysis-fresh-comparison',started:new Date().toISOString(),files,inputs,cpu:2,node:process.version,repetitions:config.repetitions??3,scope:'Alternating fresh single-API processes on CPU2,3GiB heap, prepared per-API validated Base outside compile interval. Successful exact-output compilation; program execution where applicable, library bytes fully consumed by SHA-256. Earlier resource-interrupted dual-API observations excluded.',rows:[],complete:false};const reportFile=path.join(out,'report.json'),flush=()=>save(reportFile,report);flush();
 async function child(name,args,timeoutMs){const stdout=path.join(out,name+'.stdout'),stderr=path.join(out,name+'.stderr'),a=fs.openSync(stdout,'wx'),b=fs.openSync(stderr,'wx'),start=performance.now();return await new Promise((resolve,reject)=>{const command=['taskset','-c','2',process.execPath,...args],p=spawn(command[0],command.slice(1),{stdio:['ignore',a,b],detached:true});fs.closeSync(a);fs.closeSync(b);let error;const kill=()=>{try{process.kill(-p.pid,'SIGKILL');}catch{}};const alarm=setTimeout(()=>{error='deadline';kill();},timeoutMs);const monitor=setInterval(()=>{if(fs.statSync(stdout).size+fs.statSync(stderr).size>1048576){error='output limit';kill();}},20);p.on('error',e=>{error=e.message;});p.on('close',(status,signal)=>{clearTimeout(alarm);clearInterval(monitor);resolve({command,status,signal,error,wallMs:performance.now()-start,stdout,stderr,stdoutSha256:sha(stdout),stderrSha256:sha(stderr)});});});}
 try{let expected;
 for(let round=0;round<report.repetitions;round++)for(const variant of round%2?['candidate','plain']:['plain','candidate']){
  const id=variant+'-'+round,request={api:files[variant==='plain'?'baseline':'candidate'],host:files.host,runtime:files.runtime,base:files.base,input:files.input,mode:config.mode??'compile',inputs,output:path.join(out,id+'.mjs'),result:path.join(out,id+'.json')},file=path.join(out,id+'-request.json');save(file,request);const row={round,variant,started:new Date().toISOString(),passed:false};report.rows.push(row);flush();
  row.process=await child(id,['--stack-size=4096','--max-old-space-size=3072',import.meta.filename,'--worker',file],config.timeoutMs??180000);assert.equal(row.process.status,0,JSON.stringify(row.process));assert.equal(row.process.error,undefined);row.compilation=JSON.parse(fs.readFileSync(request.result));expected??=row.compilation.outputSha256;assert.equal(row.compilation.outputSha256,expected);
  if(config.mode==='library'){row.execution={skipped:true,reason:'Library-only component; complete emitted bytes consumed by SHA-256 and compared exactly.'};}else{row.execution=await child(id+'-execute',['--stack-size=4096',request.output],30000);assert.equal(row.execution.status,0);assert.equal(fs.readFileSync(row.execution.stdout,'utf8'),config.stdout);assert.equal(fs.readFileSync(row.execution.stderr,'utf8'),'');}row.passed=true;row.finished=new Date().toISOString();flush();console.log(JSON.stringify({round,variant,compileMs:row.compilation.compileMs,processMs:row.process.wallMs,maxRssKiB:row.compilation.maxRssKiB}));
 }
 const median=xs=>[...xs].sort((a,b)=>a-b)[Math.floor(xs.length/2)];report.medians=Object.fromEntries(['plain','candidate'].map(v=>{const rows=report.rows.filter(r=>r.variant===v);return [v,{compileMs:median(rows.map(r=>r.compilation.compileMs)),processMs:median(rows.map(r=>r.process.wallMs)),phases:Object.fromEntries(['check_from_exact_prefix','annotate_selected','j_layout_error','j_program_selected'].map(name=>[name,median(rows.map(r=>r.compilation.phases.filter(p=>p.name===name).reduce((n,p)=>n+p.milliseconds,0)))]))}];}));
 report.inputsUnchanged=Object.entries(inputs).every(([f,h])=>sha(f)===h);assert.equal(report.inputsUnchanged,true);report.complete=true;
 }catch(error){report.error=error.stack;process.exitCode=1;}finally{report.finished=new Date().toISOString();flush();}
}
