// Exact normalization controls for a checked Bend-generated H capsule.
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {spawnSync} from 'node:child_process';
const [configArg,outArg]=process.argv.slice(2);if(!outArg)throw Error('usage: analysis-h-gate.mjs CONFIG.json NEW_DIRECTORY');
const cfg=JSON.parse(fs.readFileSync(configArg)),resolve=f=>fs.realpathSync(path.resolve(path.dirname(path.resolve(configArg)),f)),out=path.resolve(outArg);fs.mkdirSync(out,{recursive:false});
const files=Object.fromEntries(['baseline','candidate','host','runtime','base'].map(k=>[k,resolve(cfg[k])])),sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),digest=s=>crypto.createHash('sha256').update(s).digest('hex');
const abiFile=path.join(path.dirname(files.host),'compiler-abi.mjs'),{createCompilerAbi}=await import(pathToFileURL(abiFile));
const fields={Nil:[],Con:['head','tail'],KTerm:['tag','name','id','quant','kids','removed'],KDef:['name','kind','arity','templates','typ','value','ctors','native','unsafe']};
const apis={};for(const [variant,key] of [['plain','baseline'],['candidate','candidate']]){const module=await import(pathToFileURL(files[key]));apis[variant]=createCompilerAbi({fields,ctor:module.ctor}).wrap(module.default);}
const report={kind:'phase4-H-normalization-differential-gate',started:new Date().toISOString(),files,inputs:Object.fromEntries([...Object.values(files),abiFile,import.meta.filename,configArg].map(f=>[fs.realpathSync(f),sha(f)])),scope:'Checked Bend-emitted wnf capsule in frozen H; exact term equality plus existing normalization controls. No whole-compiler fixed point asserted.',controls:[],complete:false},save=()=>fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');save();
const nil={$:'Nil'},list=xs=>xs.reduceRight((tail,head)=>({$:'Con',head,tail}),nil),t=(tag,name='',id=0,kids=[],removed=[])=>({$:'KTerm',tag,name,id,quant:0,kids:list(kids),removed:list(removed)}),variable=t('Var','x',1),truth=t('Ctr','True'),beta=t('App','',0,[t('Lam','x',1,[variable]),truth]);
const terms=[t('Var','x',1,[beta]),variable,beta,t('Ann','',0,[beta,t('ADT','B')]),t('All','x',1,[beta,beta]),t('ADT','Family',0,[beta],['No']),t('All'),t('ADT'),t('Ref','missing'),t('Ctr','Box',0,[beta]),t('Typ','',0,[t('Qua')]),t('Rwt','',0,[t('Rfl'),t('Absent'),beta]),t('Min','',0,[t('Qua'),t('Qua')])];
for(let i=0;i<64;i++)terms.push(t(i%2?'All':'ADT','name'+i,i,[terms[i%13],terms[(i*7)%13]],i%3?[]:['Excluded']));
try{
 for(let index=0;index<terms.length;index++){const term=terms[index],expected=apis.plain.wnf(nil,term),actual=apis.candidate.wnf(nil,term);assert.deepEqual(actual,expected);if(term.tag==='All'||term.tag==='ADT')assert.deepEqual(actual,term);report.controls.push({index,tag:term.tag,outputSha256:digest(JSON.stringify(expected)),exact:true});}
 const view=path.join(out,'candidate-view.mjs');fs.writeFileSync(view,'import * as M from '+JSON.stringify(pathToFileURL(files.candidate).href)+';import {createCompilerAbi} from '+JSON.stringify(pathToFileURL(abiFile).href)+';export default createCompilerAbi({fields:'+JSON.stringify(fields)+',ctor:M.ctor}).wrap(M.default);\n');
 const test=resolve(cfg.normalizationTest),result=spawnSync(process.execPath,['--stack-size=4096','--max-old-space-size=3072',test],{env:{...process.env,BEND_NORMALIZE_API:view},encoding:'utf8',timeout:120000,maxBuffer:1048576});report.normalization={file:test,sha256:sha(test),status:result.status,signal:result.signal,error:result.error?.message,stdout:result.stdout,stderr:result.stderr};assert.equal(result.status,0,result.stderr||result.stdout);
 report.inputsUnchanged=Object.entries(report.inputs).every(([f,h])=>sha(f)===h);assert.equal(report.inputsUnchanged,true);report.complete=true;
}catch(error){report.error=error.stack;process.exitCode=1;}finally{report.finished=new Date().toISOString();save();console.log(JSON.stringify({complete:report.complete,controls:report.controls.length,error:report.error}));}
