// Controlled source-candidate/H/B1/pinned-TS comparison with asynchronous file-backed supervision.
// Derived from the Phase 3 exact comparison; Phase 4 adds checked-overlay provenance.
import fs from 'node:fs';import path from 'node:path';import {spawn} from 'node:child_process';import {createHash} from 'node:crypto';import {fileURLToPath,pathToFileURL} from 'node:url';import assert from 'node:assert/strict';
const tool=fileURLToPath(import.meta.url),sha=file=>createHash('sha256').update(fs.readFileSync(file)).digest('hex'),identity=file=>({canonicalPath:fs.realpathSync(file),sha256:sha(file)}),save=(file,value)=>fs.writeFileSync(file,JSON.stringify(value,null,2)+'\n');
function verify(inputs){for(const [file,before] of Object.entries(inputs))assert.deepEqual(identity(file),before,'Consumed artifact changed: '+file);}
function readLog(file){const bytes=fs.statSync(file).size,fd=fs.openSync(file,'r');try{const n=Math.min(bytes,2**20),buffer=Buffer.alloc(n);fs.readSync(fd,buffer,0,n,0);return {file,bytes,sha256:sha(file),truncated:bytes>n,text:buffer.toString('utf8')};}finally{fs.closeSync(fd);}}
async function capture(command,args,{cwd,prefix,timeoutMs,env}){
 const stdout=prefix+'.stdout',stderr=prefix+'.stderr',a=fs.openSync(stdout,'w'),b=fs.openSync(stderr,'w'),start=performance.now();let status=null,signal=null,error,timedOut=false;
 try{await new Promise(resolve=>{const child=spawn(command,args,{cwd,env,detached:true,stdio:['ignore',a,b]});const timer=setTimeout(()=>{timedOut=true;try{process.kill(-child.pid,'SIGKILL')}catch(e){if(e.code!=='ESRCH')error=e}},timeoutMs);child.once('error',e=>{error=e;clearTimeout(timer);resolve()});child.once('close',(code,sig)=>{status=code;signal=sig;clearTimeout(timer);resolve()})})}finally{fs.closeSync(a);fs.closeSync(b)}
 return {command,args,wallMs:performance.now()-start,status,signal,timedOut,error:error?.message,stdout:readLog(stdout),stderr:readLog(stderr)};
}
const semantic=(r,lane)=>({status:r.status,phase:r.phase,checked:r.checked===true,exitCode:r.exitCode??null,diagnostic:r.diagnostic??null,stdout:lane==='check'?(r.stdout??''):''});
if(['--prime','--sample'].includes(process.argv[2])){
 const req=JSON.parse(fs.readFileSync(process.argv[3]));verify(req.identities);process.env.BEND_UPSTREAM=req.upstream;process.env.BEND_BASE=req.base;process.env.BEND_TYPED_RUNTIME=req.runtime;delete process.env.BEND_TYPED_TRACE;
 let D,api,session,B,C;
 if(req.variant.kind==='bend'){process.env.BEND_TYPED_API=req.variant.api;D=await import(pathToFileURL(req.host));api=await D.loadApi();}
 else{const adapter=await import(pathToFileURL(req.reference));session=await adapter.createPersistentSession();B=await import(pathToFileURL(path.join(req.upstream,'bend2/bend.ts')));C=await import(pathToFileURL(path.join(req.upstream,'bend2/comp.ts')));}
 if(process.argv[2]==='--prime'){
  assert.equal(req.variant.kind,'bend');const start=performance.now(),cache=await D.prepareBase(api),milliseconds=performance.now()-start,location=createHash('sha256').update(fs.realpathSync(req.base)).digest('hex'),cacheFile=path.join(D.project,'build/typed/cache',`base-${sha(req.variant.api)}-${sha(req.base)}-${location}.json`);
  const dependencies=[...new Set(req.workloads.flatMap(work=>D.discoverSources(api,work.input,{seed:cache}).files))];verify(req.identities);save(req.result,{milliseconds,cacheFile,cacheIdentity:identity(cacheFile),validatedBy:cache.validatedBy,compilerSha256:cache.compilerSha256,baseSha256:cache.baseSha256,bookSha256:cache.bookSha256,sourcePath:cache.sourcePath,dependencies});
 }else{
  const start=performance.now();let result,code;
  if(req.variant.kind==='bend'){result=await D.inspect(req.input,{api,mode:req.lane==='emit'?'compile':req.lane});code=result.code;delete result.code;}
  else if(req.lane!=='emit')result=await session.probe({test:{file:req.input},lane:req.lane,workdir:req.workdir,timeoutMs:req.timeoutMs,upstream:req.upstream});
  else{let phase='parse',checked=false;try{const book=B.book_nil();await B.book_load(book,req.input,'',new Map());phase='check';checked=true;B.book_valid(book);phase='compile';C.book_owned(book,C.SYNTH);phase='check';const holes=book.hols+book.open;if(holes)throw `Error: ${holes} TODO${holes===1?'':'s'} found.\nThe code is incomplete, and not a valid proof yet.`;phase='compile';code=C.js_book(book);result={status:'ok',phase,checked,exitCode:0};}catch(error){result={status:'error',phase,checked,exitCode:1,diagnostic:error?.$==='Err'?B.err_show(error):String(error)};}}
  const compileMs=performance.now()-start;
  let emitted=null;if(code!==undefined){fs.writeFileSync(req.output,code);emitted={file:req.output,bytes:Buffer.byteLength(code),sha256:sha(req.output)};}
  verify(req.identities);save(req.result,{variant:req.variant.id,lane:req.lane,compileMs,result,semantic:semantic(result,req.lane),emitted,node:{path:process.execPath,version:process.version,args:process.execArgv},affinity:fs.readFileSync('/proc/self/status','utf8').split('\n').find(line=>line.startsWith('Cpus_allowed_list:')),artifacts:req.identities});
 }
}else{
 const [configArg,outArg]=process.argv.slice(2);if(!outArg)throw Error('Usage: final-compiler-compare.mjs CONFIG.json NEW_OUTPUT_DIRECTORY');const configFile=fs.realpathSync(configArg),config=JSON.parse(fs.readFileSync(configFile)),resolve=file=>fs.realpathSync(path.resolve(path.dirname(configFile),file)),out=path.resolve(outArg);fs.mkdirSync(out,{recursive:false});
 const upstream=resolve(config.upstream),base=resolve(config.base),runtime=resolve(config.runtime),driver=resolve(config.driver),cpu=config.cpu,repetitions=config.repetitions??3,timeoutMs=config.timeoutMs??120000;
 assert.ok(Number.isSafeInteger(cpu)&&cpu>=0);assert.ok(Number.isSafeInteger(repetitions)&&repetitions>0);assert.equal(base,fs.realpathSync(path.join(upstream,'bend2/base.bend')),'TS and Bend must use the exact same canonical Base');
 const pin='6018e28ecc67cf1fffc0c20c64b11023474c2df8',revision=await capture('git',['-C',upstream,'rev-parse','HEAD'],{cwd:out,prefix:path.join(out,'git-revision'),timeoutMs:30000,env:process.env});assert.equal(revision.error,undefined);assert.equal(revision.status,0);assert.equal(revision.stdout.text.trim(),pin);const clean=await capture('git',['-C',upstream,'diff','--quiet','HEAD','--','bend2','tests'],{cwd:out,prefix:path.join(out,'git-clean'),timeoutMs:30000,env:process.env});assert.equal(clean.error,undefined);assert.equal(clean.status,0,'Pinned upstream compiler and fixtures must be clean');
 const variants=config.variants.map(v=>{assert.ok(/^[-a-z0-9_]+$/.test(v.id)&&['bend','typescript'].includes(v.kind));return {...v,...(v.kind==='bend'?{api:resolve(v.api)}:{}),...(v.embeddedRuntime?{embeddedRuntime:resolve(v.embeddedRuntime)}:{})};});assert.equal(new Set(variants.map(v=>v.id)).size,variants.length);assert.equal(variants.filter(v=>v.kind==='typescript').length,1);
 const workloads=config.workloads.map(w=>({...w,input:resolve(w.input),lanes:w.lanes??(w.expectedStatus==='error'?['parse','check']:['parse','check','emit'])}));assert.equal(new Set(workloads.map(w=>w.id)).size,workloads.length);for(const w of workloads){assert.match(w.id,/^[-a-z0-9_]+$/);assert.ok(['ok','error'].includes(w.expectedStatus));assert.ok(w.lanes.every(l=>['parse','check','emit'].includes(l)));if(w.lanes.includes('emit'))assert.equal(w.expectedStatus,'ok');}
 const identities=Object.fromEntries([tool,configFile,process.execPath,base,runtime,...['bend.ts','comp.ts','base.bend','main.ts'].map(f=>path.join(upstream,'bend2',f)),...workloads.map(w=>w.input)].map(file=>[file,identity(file)]));
 const hostDir=path.join(out,'host/tools');fs.mkdirSync(hostDir,{recursive:true});for(const name of ['typed-driver','compiler-abi','node-resource-args','assemble','native-build']){const original=name==='typed-driver'?driver:path.join(path.dirname(driver),name+'.mjs'),copied=path.join(hostDir,name+'.mjs');fs.copyFileSync(original,copied);identities[copied]=identity(copied);}
 const host=path.join(hostDir,'typed-driver.mjs'),reference=path.join(hostDir,'conformance/adapters/upstream.mjs');fs.mkdirSync(path.dirname(reference),{recursive:true});fs.copyFileSync(resolve(config.referenceAdapter),reference);identities[reference]=identity(reference);
 const addRecorded=record=>{assert.ok(record?.file&&record.canonicalPath&&record.sha256,'Missing recorded identity');assert.deepEqual(identity(record.file),{canonicalPath:record.canonicalPath,sha256:record.sha256},'Recorded provenance changed: '+record.file);identities[record.file]=identity(record.file);};
 if(config.seedCacheDirectory){const seed=resolve(config.seedCacheDirectory),target=path.join(out,'host/build/typed/cache');fs.mkdirSync(target,{recursive:true});for(const name of fs.readdirSync(seed).filter(n=>/^base-.*\.json$/.test(n))){const original=path.join(seed,name);identities[original]=identity(original);fs.copyFileSync(original,path.join(target,name));}}
 const worker=path.join(out,'worker.mjs');fs.copyFileSync(tool,worker);identities[worker]=identity(worker);const provenance=[];
 for(const variant of variants.filter(v=>v.kind==='bend')){
  identities[variant.api]=identity(variant.api);if(variant.embeddedRuntime){identities[variant.embeddedRuntime]=identity(variant.embeddedRuntime);assert.ok(fs.readFileSync(variant.api,'utf8').startsWith(fs.readFileSync(variant.embeddedRuntime,'utf8')),'Compiler embedded runtime prefix differs');}
  for(const [i,p] of (variant.provenance??[]).entries()){const original=resolve(p),snapshot=path.join(out,variant.id+'-provenance-'+i+'.json');fs.copyFileSync(original,snapshot);identities[snapshot]=identity(snapshot);const record=JSON.parse(fs.readFileSync(snapshot));provenance.push({variant:variant.id,original,snapshot,sha256:sha(snapshot),complete:record.complete??null});
   if(record.kind==='phase4-checked-overlay'){assert.equal(record.complete,true);assert.equal(record.inputsUnchanged,true);assert.equal(record.api.sha256,sha(variant.api));addRecorded(record.source);for(const input of record.inputs)addRecorded(input);}
   if(record.kind==='phase4-frozen-baseline'){const relative=path.relative(record.root,variant.api),entry=record.files[relative];assert.ok(entry,'Selected API must be in frozen manifest');assert.equal(entry.sha256,sha(variant.api));assert.equal(record.base.sha256,sha(base));}
   if(record.kind==='bend-private-compiler-image'){
    assert.equal(record.complete,true);assert.equal(record.proofStatus,'fixedpoint');
    assert.equal(variant.api,path.join(path.dirname(original),'image.mjs'));
    assert.equal(record.runtime.sha256,sha(runtime));assert.equal(record.base.canonicalPath,base);addRecorded(record.base);
    const relatives=new Set();
    for(const artifact of record.artifacts){
     assert.ok(typeof artifact.relative==='string'&&!path.isAbsolute(artifact.relative)&&!artifact.relative.split(path.sep).includes('..')&&!relatives.has(artifact.relative),'Invalid or duplicate private artifact');relatives.add(artifact.relative);
     const file=path.join(path.dirname(original),artifact.relative);assert.ok(fs.realpathSync(file).startsWith(fs.realpathSync(path.dirname(original))+path.sep));assert.equal(sha(file),artifact.sha256);identities[file]=identity(file);
    }
    assert.ok(relatives.has('image.mjs')&&relatives.has('runtime.mjs')&&relatives.has('provenance/proof.json'));
   }
   if(record.kind==='phase3-checked-integration-api'){assert.equal(record.complete,true);assert.equal(record.apiSha256,sha(variant.api));assert.equal(record.sourceSha256,sha(record.source));assert.equal(record.provenance?.verifiedAfterBuild,true);assert.ok(record.provenance.inputs.length>0);for(const input of record.provenance.inputs)addRecorded(input);identities[record.source]=identity(record.source);}
   if(record.stage==='upstream-bootstrap'){assert.equal(record.apiSha256,sha(variant.api));assert.equal(record.baseSha256,sha(base));assert.equal(record.sourceSha256,sha(record.source));identities[record.source]=identity(record.source);for(const m of record.modules){const file=path.join(path.dirname(record.source),m.file);assert.equal(sha(file),m.sha256);identities[file]=identity(file);}}
   if(record.kind==='phase3-frozen-phase2-baseline'){const entry=record.files.find(f=>path.resolve(record.root,f.file)===variant.api);assert.ok(entry,'Baseline manifest must contain selected API');assert.equal(entry.sha256,sha(variant.api));assert.equal(record.baseSha256,sha(base));}
   if(Array.isArray(record.stages)){for(const input of [record.sourceIdentity,record.base,record.driver,record.initialCompiler,...(record.hostHelpers??[])])addRecorded(input);assert.equal(record.base.sha256,sha(base));assert.ok(record.hostHelpers.length>=4);const stage=record.stages.find(s=>s.output===variant.api||s.file===variant.api||s.outputSha256===sha(variant.api)||s.sha256===sha(variant.api));assert.ok(stage,'Wait for the completed API emission to be recorded before benchmarking');assert.equal(stage.code,0);assert.equal(stage.inputsVerified,true);assert.equal(stage.outputSha256,sha(variant.api));assert.equal(stage.compilerSha256,sha(stage.compiler));identities[stage.compiler]=identity(stage.compiler);if(variant.embeddedRuntime)assert.equal(record.runtimeSha256,sha(variant.embeddedRuntime));if(record.source&&record.sourceSha256){assert.equal(sha(record.source),record.sourceSha256);identities[record.source]=identity(record.source);}}
  }
 }
 const nodeArgs=['--stack-size=4096','--max-old-space-size=4096'],report={kind:'phase4-controlled-compiler-comparison',started:new Date().toISOString(),complete:false,scope:'One shared frozen current host for all Bend APIs, one shared output runtime for their generated programs. Each compiler retains its own embedded runtime. Pinned TS retains its own compiler and generated runtime. Fresh processes, exact diagnostic/check text and observed program outputs; JS bytes compared only between Bend compilers when requested. Parse/check/emit latencies are cumulative request scopes, not additive phase timings.',cachePolicy:'Separate validated Base cache per Bend API is primed before timing. Pinned TS has no equivalent serialized compiler-side Base cache and loads/checks Base in each process. OS caches are not flushed.',upstream:{path:upstream,pin},seedCacheDirectory:config.seedCacheDirectory??null,orderPolicy:'Original variant order in even repetitions; reverse order in odd repetitions. Every pair alternates relative order.',base,runtime,host,reference,variants,workloads,provenance,identities,cpu,repetitions,node:{path:process.execPath,version:process.version,args:nodeArgs},warm:{},rows:[],failures:[]};const flush=()=>save(path.join(out,'report.json'),report);flush();
 const child=async(mode,req,name)=>{const request=path.join(out,name+'-request.json');save(request,{...req,identities:{...identities}});const processResult=await capture('taskset',['-c',String(cpu),process.execPath,...nodeArgs,worker,mode,request],{cwd:out,prefix:path.join(out,name),timeoutMs,env:{...process.env,NODE_OPTIONS:''}});return {...processResult,request};};
 const common={upstream,base,runtime,host,reference,timeoutMs};
 for(const variant of variants.filter(v=>v.kind==='bend')){const result=path.join(out,'prime-'+variant.id+'.json'),processResult=await child('--prime',{...common,variant,workloads,result},'prime-'+variant.id);if(processResult.status!==0||processResult.error){report.failures.push({kind:'prime',variant:variant.id,process:processResult});flush();throw Error('Cache preparation failed; see retained logs: '+variant.id);}const warmed=JSON.parse(fs.readFileSync(result));assert.equal(warmed.validatedBy,'check_book');report.warm[variant.id]={...warmed,process:processResult};identities[warmed.cacheFile]=warmed.cacheIdentity;for(const file of warmed.dependencies)identities[file]=identity(file);flush();}
 for(let repetition=0;repetition<repetitions;repetition++)for(const work of workloads)for(const lane of work.lanes){const order=repetition%2?[...variants].reverse():variants;for(const variant of order){
  const name=work.id+'-'+lane+'-'+repetition+'-'+variant.id,workdir=path.join(out,name+'-files');fs.mkdirSync(workdir);const result=path.join(workdir,'result.json'),output=path.join(workdir,variant.kind==='typescript'?'program.cjs':'program.mjs');console.error('[final compiler comparison] '+name);
  const processResult=await child('--sample',{...common,variant,input:work.input,lane,workdir,output,result},name),row={workload:work.id,lane,repetition,variant:variant.id,process:processResult,passed:false};report.rows.push(row);
  if(processResult.status===0&&!processResult.error&&!processResult.stdout.truncated&&!processResult.stderr.truncated&&fs.existsSync(result)){row.observation=JSON.parse(fs.readFileSync(result));const got=row.observation.semantic,expectedStatus=lane==='parse'?'ok':work.expectedStatus;row.expected=got.status===expectedStatus&&got.phase===(lane==='emit'?'compile':lane)&&got.checked===(lane!=='parse')&&got.exitCode===(expectedStatus==='ok'?0:1);
   const peers=report.rows.filter(other=>other!==row&&other.workload===work.id&&other.lane===lane&&other.observation);row.exactOutcomeEqual=peers.every(peer=>JSON.stringify(peer.observation.semantic)===JSON.stringify(got));row.passed=row.expected&&row.exactOutcomeEqual;
   if(lane==='emit'&&row.expected){const emitted=row.observation.emitted;if(!emitted)row.passed=false;else{row.execution=await capture(process.execPath,[...nodeArgs,output],{cwd:workdir,prefix:path.join(workdir,'execution'),timeoutMs,env:{...process.env,NODE_OPTIONS:''}});row.executionPassed=row.execution.status===0&&!row.execution.error&&!row.execution.signal&&!row.execution.stdout.truncated&&!row.execution.stderr.truncated&&row.execution.stdout.text===work.expectedStdout&&row.execution.stderr.text==='';row.passed&&=row.executionPassed;
    if(config.requireBendBytes!==false&&variant.kind==='bend'){const bendPeers=peers.filter(peer=>variants.find(v=>v.id===peer.variant)?.kind==='bend'&&peer.observation.emitted);row.sameBendBytes=bendPeers.every(peer=>peer.observation.emitted.sha256===emitted.sha256);row.passed&&=row.sameBendBytes;}
   }}
  }
  if(!row.passed)report.failures.push({workload:work.id,lane,variant:variant.id,repetition});flush();
 }}
 const median=xs=>{const sorted=[...xs].sort((a,b)=>a-b);return sorted[Math.floor(sorted.length/2)];};report.summary=Object.fromEntries(workloads.map(work=>[work.id,Object.fromEntries(work.lanes.map(lane=>[lane,Object.fromEntries(variants.map(variant=>{const cell=report.rows.filter(r=>r.workload===work.id&&r.lane===lane),rows=cell.filter(r=>r.variant===variant.id),validComparison=cell.length===repetitions*variants.length&&cell.every(r=>r.passed);return [variant.id,{samples:rows.length,passedSamples:rows.filter(r=>r.passed).length,validComparison,...(validComparison?{medianRequestMs:median(rows.map(r=>r.observation.compileMs)),medianProcessWallMs:median(rows.map(r=>r.process.wallMs)),...(lane==='emit'?{medianExecutionWallMs:median(rows.map(r=>r.execution.wallMs))}:{})}:{timingsWithheld:'The complete comparison cell did not pass exact outcome/byte/execution gates.'})}];}))]))]));
 verify(identities);report.complete=report.failures.length===0&&report.rows.length===repetitions*variants.length*workloads.reduce((n,w)=>n+w.lanes.length,0);report.finished=new Date().toISOString();flush();console.log(JSON.stringify({output:out,complete:report.complete,summary:report.summary,failures:report.failures}));if(!report.complete)process.exitCode=1;
}
